import Suzuki

-- This exact-version audit intentionally names generated auxiliary declarations.
-- Suppress only the warning against referencing such names across refactors.
set_option linter.auxLemma false

-- Every compiled declaration in the Suzuki namespace, including generated ones.
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap._proof_2
#print axioms Suzuki.CommonCorner.Frame.gram_projection
#print axioms Suzuki.MultiplicityEmbeddings.intoDimensions_injective
#print axioms Suzuki.FiniteDiagram.Realization.noConfusionType
#print axioms Suzuki.PositiveLifting.Kernel
#print axioms Suzuki.RFDAmplification.flatten._proof_2
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra_closed
#print axioms Suzuki.UnitizationRFD.extend._proof_6
#print axioms Suzuki.FiniteCPApproximation.Blocks
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.hom_ext
#print axioms Suzuki.CommonCorner.corner_hom_ext
#print axioms Suzuki.MatrixLimits.matrixHom_apply
#print axioms Suzuki.FiniteDiagram.natMatrix
#print axioms Suzuki.CommonCorner.Frame.mk.injEq
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.limitRetraction_contractive
#print axioms Suzuki.InductiveAmalgam.System.algebra
#print axioms Suzuki.FiniteCPApproximation.blockInclusion._proof_2
#print axioms Suzuki.SequentialCStarLimit.map
#print axioms Suzuki.MultiplicityEmbeddings.exists_exact_square
#print axioms Suzuki.ResidualRepresentations.Representation.casesOn
#print axioms Suzuki.InductiveAmalgam.System.Hom._sizeOf_inst
#print axioms Suzuki.CommonCorner.toCornerHom._proof_4
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.mk.noConfusion
#print axioms Suzuki.CommonCorner.cornerPartialOrder
#print axioms Suzuki.CommonCorner.rowCompression._proof_1
#print axioms Suzuki.FiniteCPApproximation.homCP
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom._proof_2
#print axioms Suzuki.MatrixRetractions.entryCP._proof_1
#print axioms Suzuki.DirectedCStarLimit.lift_unique
#print axioms Suzuki.InductiveAmalgam.System.mk
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv_left
#print axioms Suzuki.FiniteCPApproximation.amplifyHom
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_2
#print axioms Suzuki.CommonCorner.inclusion_apply
#print axioms Suzuki.CommonCorner.Frame
#print axioms Suzuki.CommonCorner.Frame.representation._proof_8
#print axioms Suzuki.CommonCorner.compress._proof_4
#print axioms Suzuki.CommonCorner.Frame.representation._proof_13
#print axioms Suzuki.CornerPureInfiniteness.right_support_of_square
#print axioms Suzuki.MultiplicityEmbeddings.compositions_unitarily_conjugate
#print axioms Suzuki.CornerSimplicity.nontrivial
#print axioms Suzuki.SequentialCStarLimit.transitionInjective
#print axioms Suzuki.ResidualRepresentations.Representation.ctorIdx
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_16
#print axioms Suzuki.MatrixRetractions.singleHom._proof_2
#print axioms Suzuki.FiniteDiagram.Realization.right_multiplicity
#print axioms Suzuki.CommonCorner.Frame.representation._proof_4
#print axioms Suzuki.CommonCorner.Frame.matrixHom
#print axioms Suzuki.FiniteCPApproximation.cpComp_apply
#print axioms Suzuki.PositiveLifting.row_sum_le_mul
#print axioms Suzuki.Target.UnitalAlgebra._sizeOf_1
#print axioms Suzuki.DirectedCStarLimit.algebraicLift._proof_2
#print axioms Suzuki.SequentialCStarLimit.transition_apply
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_5
#print axioms Suzuki.CommonCorner.toCornerHom._proof_20
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom._proof_1
#print axioms Suzuki.Target.HasCPApproximation
#print axioms Suzuki.MatrixLimits.matrixHom
#print axioms Suzuki.FiniteDiagram.identity_nonnegative._proof_1_1
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv._proof_3
#print axioms Suzuki.ResidualRepresentations.Representation
#print axioms Suzuki.MatrixRetractions.coordinateEquiv._proof_4
#print axioms Suzuki.CStarCompletion.completionStarModule._simp_1
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_2
#print axioms Suzuki.SimpleTraces.faithful_of_simple
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift_stage
#print axioms Suzuki.PositiveLifting.coordinateEquiv
#print axioms Suzuki.CommonCorner.map._proof_3
#print axioms Suzuki.FiniteDiagram.Realization.mk.inj
#print axioms Suzuki.CornerSimplicity.ideals_trivial._simp_1_1
#print axioms Suzuki.MatrixRetractions.coordinateEquiv._proof_5
#print axioms Suzuki.CornerSimplicity.isSimple
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.casesOn
#print axioms Suzuki.CommonCorner.rowCompression._proof_5
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv_isometry
#print axioms Suzuki.SequentialCStarLimit.compatible_transition
#print axioms Suzuki.ResidualRepresentations.Representation._sizeOf_1
#print axioms Suzuki.FiniteDiagram.identity_nonnegative
#print axioms Suzuki.FiniteDiagram.integer_realization
#print axioms Suzuki.CommonCorner.cornerRing._aux_5
#print axioms Suzuki.MatrixDiagrams.first_square._abel_1_3
#print axioms Suzuki.CPApproximationLimits.CPCSplitting._sizeOf_1
#print axioms Suzuki.SequentialCStarLimit.map_injective
#print axioms Suzuki.MatrixDiagrams.diagram.congr_simp
#print axioms Suzuki.CommonCorner.map._proof_14
#print axioms Suzuki.MultiplicityEmbeddings.copyHom._proof_6
#print axioms Suzuki.CommonCorner.Frame.ofApproximation._proof_2
#print axioms Suzuki.SequentialCStarLimit.stage_isometry
#print axioms Suzuki.InductiveAmalgam.System.Hom._sizeOf_1
#print axioms Suzuki.CornerFiniteness.complementHom._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_1
#print axioms Suzuki.FiniteDiagram.natMatrix_first
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_10
#print axioms Suzuki.MultiplicityEmbeddings.exists_copy_reindex_of_counts
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.mk
#print axioms Suzuki.PositiveLifting.homotopy_cokernel
#print axioms Suzuki.StableFiniteness.FaithfulTrace.nonnegative
#print axioms Suzuki.UnitizationRFD.augmentation._proof_3
#print axioms Suzuki.CStarCompletion.lift._proof_2
#print axioms Suzuki.MultiplicityEmbeddings.natCast_toNat_multiplicity
#print axioms Suzuki.StableFiniteness.amplification._proof_2
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.mk
#print axioms Suzuki.DirectedCStarLimit.hom_ext
#print axioms Suzuki.FiniteDiagram.Realization.right_dimensions
#print axioms Suzuki.CommonCorner.ofSupport._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_comp_lift
#print axioms Suzuki.MatrixLimits.limitStarOrderedRing
#print axioms Suzuki.ResidualRepresentations.Representation.mk
#print axioms Suzuki.SequentialCStarLimit.stage_injective
#print axioms Suzuki.MatrixRetractions.singleHom
#print axioms Suzuki.CornerPureInfiniteness.isInfiniteProjection
#print axioms Suzuki.MultiplicityEmbeddings.Blocks
#print axioms Suzuki.InductiveAmalgam.System.noConfusion
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting
#print axioms Suzuki.StableFiniteness.FaithfulTrace.recOn
#print axioms Suzuki.CommonCorner.coe_ofSupport
#print axioms Suzuki.MatrixRetractions.coordinateEquiv._proof_3
#print axioms Suzuki.SequentialCStarLimit.transition.eq_1
#print axioms Suzuki.MultiplicityEmbeddings.intoDimensions.eq_1
#print axioms Suzuki.MultiplicityEmbeddings.firstMultiplicity.eq_1
#print axioms Suzuki.CommonCorner.Frame.fullProjection
#print axioms Suzuki.CommonCorner.map._proof_4
#print axioms Suzuki.FiniteDiagram.Realization.target_first_isometry
#print axioms Suzuki.SequentialCStarLimit.dense_stage_union
#print axioms Suzuki.SimpleTraces.null_left
#print axioms Suzuki.CommonCorner.toCornerHom
#print axioms Suzuki.CommonCorner.Frame.support
#print axioms Suzuki.InductiveAmalgam.isFullAmalgam_canonical
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.limitRetraction_same_stage
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_3
#print axioms Suzuki.CommonCorner.cornerRing._aux_1
#print axioms Suzuki.DirectedCStarLimit.limitCStarAlgebra._proof_2
#print axioms Suzuki.FiniteDiagram.natMatrix_positive
#print axioms Suzuki.DirectedCStarLimit.stageNorm
#print axioms Suzuki.Target.UnitalAlgebra.mk.noConfusion
#print axioms Suzuki.DirectedCStarLimit.stage_injective
#print axioms Suzuki.CornerCPApproximation.isFiniteConstituent
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.mk
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.sizeOf_spec
#print axioms Suzuki.CommonCorner.cornerSubalgebra
#print axioms Suzuki.LimitCPMaps.limitOrderedRing
#print axioms Suzuki.CommonCorner.map._proof_18
#print axioms Suzuki.UnitizationRFD.extend._proof_1
#print axioms Suzuki.CommonCorner.map._proof_13
#print axioms Suzuki.FiniteCPApproximation.singleBlock_eq_compression
#print axioms Suzuki.PositiveLifting.exists_compatible_lifts
#print axioms Suzuki.StableFiniteness.FaithfulTrace.noConfusion
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom._proof_3
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.leftInverse
#print axioms Suzuki.SimpleTraces.nullIdeal._proof_1
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_5
#print axioms Suzuki.UnitizationRFD.separable
#print axioms Suzuki.ResidualRepresentations.Representation.dimension
#print axioms Suzuki.InductiveAmalgam.System.Hom.recOn
#print axioms Suzuki.MatrixLimits.dense_matrix_stage_pairs
#print axioms Suzuki.MatrixRetractions.diagonalHom._proof_6
#print axioms Suzuki.CStarCompletion.completionStarRing
#print axioms Suzuki.MultiplicityEmbeddings.compositionEnumeration
#print axioms Suzuki.FiniteDiagram.exact_square_intoDimensions
#print axioms Suzuki.FiniteCPApproximation.amplified_conjugation_entry
#print axioms Suzuki.CornerPureInfiniteness.compress_supported_sandwich
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap._unsafe_rec
#print axioms Suzuki.FiniteCPApproximation.cpZero._proof_1
#print axioms Suzuki.MatrixRetractions.diagonalHom._proof_4
#print axioms Suzuki.FiniteDiagram.Realization
#print axioms Suzuki.MultiplicityEmbeddings.copyHom_same
#print axioms Suzuki.Target.instCoeSortUnitalAlgebraType
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.mk.inj
#print axioms Suzuki.CommonCorner.toCornerHom._proof_13
#print axioms Suzuki.CommonCorner.image_one_projection
#print axioms Suzuki.Target.UnitalAlgebra.noConfusionType
#print axioms Suzuki.Target.UnitalAlgebra.noConfusion
#print axioms Suzuki.MultiplicityEmbeddings.firstMultiplicity
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_6
#print axioms Suzuki.DirectedCStarLimit.algebraicNormedRing
#print axioms Suzuki.CornerPureInfiniteness.compress_mem_hereditary
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom._proof_5
#print axioms Suzuki.OrthogonalChannels.sumHom
#print axioms Suzuki.CommonCorner.Frame.representation._proof_11
#print axioms Suzuki.CommonCorner.map._proof_19
#print axioms Suzuki.CStarCompletion.completionContinuousStar
#print axioms Suzuki.CStarCompletion.hom_ext
#print axioms Suzuki.CommonCorner.Frame.representation._proof_14
#print axioms Suzuki.Target.hereditarySet
#print axioms Suzuki.MultiplicityEmbeddings.first_targetSize
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_left
#print axioms Suzuki.CommonCorner.toCornerHom._proof_12
#print axioms Suzuki.StableFiniteness.isometry_unitary._abel_1_1
#print axioms Suzuki.SimpleFullness.closedIdeal_isClosed
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_3
#print axioms Suzuki.UnitizationRFD.Representation.casesOn
#print axioms Suzuki.FiniteDiagram.successor_positive
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span
#print axioms Suzuki.CommonCorner.Frame.equivalence_isometry
#print axioms Suzuki.StableFiniteness.FaithfulTrace.faithful
#print axioms Suzuki.Target.UnitalAlgebra.recOn
#print axioms Suzuki.CommonCorner.map._proof_15
#print axioms Suzuki.StableFiniteness.isometry_unitary
#print axioms Suzuki.CStarCompletion.lift_coe
#print axioms Suzuki.StableFiniteness.FaithfulTrace._sizeOf_inst
#print axioms Suzuki.CommonCorner.Frame.coefficient_mul
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_3
#print axioms Suzuki.ResidualRepresentations.Representation.positive_dimension
#print axioms Suzuki.CStarCompletion.completionNormedAlgebra._proof_2
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv._proof_1
#print axioms Suzuki.CommonCorner.Frame.representation._proof_21
#print axioms Suzuki.CommonCorner.Frame.coefficient._proof_2
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_11
#print axioms Suzuki.CommonCorner.map_compress
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_3
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.recOn
#print axioms Suzuki.InductiveAmalgam.System.Hom.app
#print axioms Suzuki.CommonCorner.toCornerHom._proof_10
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv_quotient
#print axioms Suzuki.CommonCorner.left_support
#print axioms Suzuki.MultiplicityEmbeddings.targetSize
#print axioms Suzuki.CStarCompletion.uniformContinuous_of_contractive
#print axioms Suzuki.FiniteDiagram.Realization.right
#print axioms Suzuki.UnitizationRFD.Representation.recOn
#print axioms Suzuki.DirectedCStarLimit.limitSeparable
#print axioms Suzuki.CommonCorner.Frame.coefficient_continuous
#print axioms Suzuki.CStarCompletion.completionStarRing._proof_4
#print axioms Suzuki.MultiplicityEmbeddings.copyHom._proof_5
#print axioms Suzuki.CommonCorner.map._proof_11
#print axioms Suzuki.MatrixLimits.stageStarOrderedRing
#print axioms Suzuki.InductiveAmalgam.limit_commutes
#print axioms Suzuki.CommonCorner.cornerStarOrderedRing
#print axioms Suzuki.UnitizationRFD.extend
#print axioms Suzuki.PositiveLifting.finite_simultaneous_positive_lifting
#print axioms Suzuki.CommonCorner.Frame.amplification_apply
#print axioms Suzuki.SimpleTraces.null_star
#print axioms Suzuki.LimitCPMaps.algebraicMap._proof_1
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap_transition
#print axioms Suzuki.CommonCorner.cornerRing._proof_3
#print axioms Suzuki.FiniteDiagram.Realization.left_isometry
#print axioms Suzuki.StableFiniteness.amplification._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.firstInclusion
#print axioms Suzuki.CornerPureInfiniteness.continuous_compress
#print axioms Suzuki.FiniteCPApproximation.homCP._proof_2
#print axioms Suzuki.CornerCPApproximation.inclusionCP._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_1
#print axioms Suzuki.MatrixRetractions.entryCP_diagonal
#print axioms Suzuki.MultiplicityEmbeddings.targetSize.eq_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_16
#print axioms Suzuki.CommonCorner.cornerAlgebra._proof_1
#print axioms Suzuki.DirectedCStarLimit.norm_mk
#print axioms Suzuki.Target.UnitalAlgebra.Carrier
#print axioms Suzuki.FiniteDiagram.Realization.mk.injEq
#print axioms Suzuki.CommonCorner.map._proof_20
#print axioms Suzuki.MultiplicityEmbeddings.CompositionCopies
#print axioms Suzuki.DirectedCStarLimit.algebraicTopology
#print axioms Suzuki.CornerFiniteness.matrixMap._proof_3
#print axioms Suzuki.DirectedCStarLimit.stageNorm_mk
#print axioms Suzuki.CommonCorner.map._proof_7
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.step_injective
#print axioms Suzuki.CommonCorner.toCornerHom._proof_18
#print axioms Suzuki.MatrixRetractions.coordinateEquiv._proof_2
#print axioms Suzuki.ResidualRepresentations.Representation.mk.noConfusion
#print axioms Suzuki.CommonCorner.Frame.ctorIdx
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_8
#print axioms Suzuki.SequentialCStarLimit.transition_self
#print axioms Suzuki.LimitCPMaps.algebraicTopology._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_5
#print axioms Suzuki.FiniteCPApproximation.matrixAlgebra
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra
#print axioms Suzuki.DirectedCStarLimit.stage_commutes
#print axioms Suzuki.CommonCorner.Frame.compressed_total
#print axioms Suzuki.MultiplicityEmbeddings.intoDimensions
#print axioms Suzuki.DirectedCStarLimit.stageNorm.congr_simp
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.finite_retraction_approx
#print axioms Suzuki.CommonCorner.toCornerHom._proof_6
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_3
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap.match_1
#print axioms Suzuki.MatrixRetractions.coordinateEquiv
#print axioms Suzuki.CommonCorner.cornerRing._proof_4
#print axioms Suzuki.CommonCorner.Frame.x
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_unique
#print axioms Suzuki.CommonCorner.map._proof_5
#print axioms Suzuki.CommonCorner.Frame._sizeOf_1
#print axioms Suzuki.Target.IsKirchberg
#print axioms Suzuki.CommonCorner.Frame.representation._proof_19
#print axioms Suzuki.OrthogonalChannels.sumHom._simp_1
#print axioms Suzuki.CStarCompletion.lift._proof_1
#print axioms Suzuki.CornerSimplicity.compress_sandwich
#print axioms Suzuki.MatrixDiagrams.second_square
#print axioms Suzuki.StableFiniteness.FaithfulTrace.cyclic
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_8
#print axioms Suzuki.CornerFiniteness.complementHom._proof_2
#print axioms Suzuki.FiniteDiagram.Realization.ctorIdx
#print axioms Suzuki.MultiplicityEmbeddings.composition_normalForm._simp_1_1
#print axioms Suzuki.CommonCorner.map._proof_9
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.splitLimit_hasCPApproximation
#print axioms Suzuki.DirectedCStarLimit.stage
#print axioms Suzuki.CommonCorner.Frame.insert
#print axioms Suzuki.CommonCorner.Frame.representation._proof_18
#print axioms Suzuki.CommonCorner.cornerRing._proof_7
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_3
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_9
#print axioms Suzuki.FiniteDiagram.intoDimensions_hasMultiplicity
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span._simp_1_2
#print axioms Suzuki.FiniteDiagram.natMatrix.eq_1
#print axioms Suzuki.StableFiniteness.FaithfulTrace._sizeOf_1
#print axioms Suzuki.RFDAmplification.flatten._proof_1
#print axioms Suzuki.FiniteDiagram.Realization.mk.sizeOf_spec
#print axioms Suzuki.FiniteCPApproximation.cpComp._proof_2
#print axioms Suzuki.CommonCorner.coe_mul
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.hom_ext
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_5
#print axioms Suzuki.DirectedCStarLimit.lift
#print axioms Suzuki.SequentialCStarLimit.stage
#print axioms Suzuki.UnitizationRFD.IsRFD
#print axioms Suzuki.LimitCPMaps.algebraicMap.congr_simp
#print axioms Suzuki.MatrixLimits.stablyFinite_of_rfd
#print axioms Suzuki.UnitizationRFD.Representation.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_3
#print axioms Suzuki.MultiplicityEmbeddings.positive_integer_multiplicity_isometry
#print axioms Suzuki.CommonCorner.coe_map
#print axioms Suzuki.ResidualRepresentations.SeparatingTails
#print axioms Suzuki.CommonCorner.Frame.representation._proof_5
#print axioms Suzuki.SimpleTraces.null_add
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom_injective
#print axioms Suzuki.RFDAmplification.finite_product_rfd
#print axioms Suzuki.ResidualRepresentations.Representation.mk.inj
#print axioms Suzuki.FiniteDiagram.Realization.common_multiplicity
#print axioms Suzuki.StableFiniteness.FaithfulTrace.noConfusionType
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.map._proof_1
#print axioms Suzuki.CommonCorner.Frame.reconstruction
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_4
#print axioms Suzuki.CStarCompletion.completionCStarRing
#print axioms Suzuki.UnitizationRFD.Representation
#print axioms Suzuki.CommonCorner.cornerRing._proof_8
#print axioms Suzuki.CommonCorner.FullProjection
#print axioms Suzuki.MatrixRetractions.diagonalHom
#print axioms Suzuki.CommonCorner.cornerAlgebra
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.splitLimitAlgebra._proof_1
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_6
#print axioms Suzuki.CStarCompletion.extension_coe
#print axioms Suzuki.SequentialCStarLimit.Limit._proof_1
#print axioms Suzuki.RFDAmplification.flatten_apply
#print axioms Suzuki.SequentialCStarLimit.map_stage
#print axioms Suzuki.IdempotentSystems.one_sub_shift_surjective
#print axioms Suzuki.CornerFiniteness.matrixMap._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_18
#print axioms Suzuki.LimitCPMaps.continuousMap_stage
#print axioms Suzuki.Target.instStarOrderedRingCarrier
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_6
#print axioms Suzuki.CommonCorner.cornerRing._proof_11
#print axioms Suzuki.StableFiniteness.FaithfulTrace.ctorIdx
#print axioms Suzuki.FiniteCPApproximation.matrix_hasCPApproximation
#print axioms Suzuki.DirectedCStarLimit.lift_stage_apply
#print axioms Suzuki.CommonCorner.cornerNormedAlgebra._proof_1
#print axioms Suzuki.UnitizationRFD.scalarRepresentation._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_20
#print axioms Suzuki.SimpleFullness.coe_closedIdeal
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap.eq_1
#print axioms Suzuki.MultiplicityEmbeddings.targetSize_comp
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_2
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_4
#print axioms Suzuki.MatrixDiagrams.second_square._abel_1_1
#print axioms Suzuki.LimitCPMaps.algebraicMap_contractive
#print axioms Suzuki.InductiveAmalgam.System.rec
#print axioms Suzuki.FiniteDiagram.HasMultiplicity
#print axioms Suzuki.MatrixRetractions.diagonalHom._proof_2
#print axioms Suzuki.CornerPureInfiniteness.coe_mem_hereditary
#print axioms Suzuki.FiniteCPApproximation.hasCPApproximation_of_retract
#print axioms Suzuki.PositiveLifting.coordinateEquiv._proof_2
#print axioms Suzuki.MultiplicityEmbeddings.targetSize_pos
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_11
#print axioms Suzuki.OrthogonalChannels.sum_mul
#print axioms Suzuki.PositiveLifting.exists_kernel_retraction
#print axioms Suzuki.DirectedCStarLimit.algebraicNormedAlgebra._proof_1
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.mk.sizeOf_spec
#print axioms Suzuki.DirectedCStarLimit.algebraicStage._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_2
#print axioms Suzuki.InductiveAmalgam.System.step
#print axioms Suzuki.IdempotentSystems.correction.eq_def
#print axioms Suzuki.Target.UnitalAlgebra.mk.inj
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm._proof_3
#print axioms Suzuki.CStarCompletion.inclusion._proof_2
#print axioms Suzuki.StableFiniteness.matrixTrace_nonnegative
#print axioms Suzuki.LimitCPMaps.algebraicMap._proof_2
#print axioms Suzuki.DirectedCStarLimit.algebraicStage._proof_2
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.sizeOf_spec
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit
#print axioms Suzuki.MatrixLimits.stageOrder
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.representation_isometry
#print axioms Suzuki.FiniteDiagram.targetDimensions_eq
#print axioms Suzuki.UnitizationRFD.Representation.rec
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv
#print axioms Suzuki.CommonCorner.FullProjection.exists_sum_one
#print axioms Suzuki.FiniteCPApproximation.blockInclusion._proof_6
#print axioms Suzuki.CStarCompletion.lift
#print axioms Suzuki.MultiplicityEmbeddings.firstInclusion_injective
#print axioms Suzuki.CommonCorner.rowCompression
#print axioms Suzuki.ResidualRepresentations.Representation.noConfusion
#print axioms Suzuki.SequentialCStarLimit.isFullAmalgam
#print axioms Suzuki.ResidualRepresentations.stablyFinite
#print axioms Suzuki.FiniteCPApproximation.amplifyHom_injective
#print axioms Suzuki.Target.IsSimple
#print axioms Suzuki.InductiveAmalgam.System.Hom.noConfusion
#print axioms Suzuki.FiniteCPApproximation.blockCompression_inclusion
#print axioms Suzuki.CornerCPApproximation.compression_contractive
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv._proof_2
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_8
#print axioms Suzuki.CommonCorner.Frame.matrixHom_apply
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_9
#print axioms Suzuki.IdempotentSystems.correction._unsafe_rec
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm._proof_6
#print axioms Suzuki.CornerCPApproximation.inclusionCP_apply
#print axioms Suzuki.MatrixDiagrams.diagram
#print axioms Suzuki.LimitCPMaps.cpMap_contractive
#print axioms Suzuki.MultiplicityEmbeddings.secondInclusion_injective
#print axioms Suzuki.CommonCorner.Frame.representation._proof_9
#print axioms Suzuki.CommonCorner.compress
#print axioms Suzuki.DirectedCStarLimit.stage._proof_2
#print axioms Suzuki.IdempotentSystems.correction.eq_2
#print axioms Suzuki.CommonCorner.toCornerHom._proof_15
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_2
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.extension
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.noConfusion
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_4
#print axioms Suzuki.FiniteDiagram.finite_prescribed_diagrams
#print axioms Suzuki.CommonCorner.Frame.matrixHom_isometry
#print axioms Suzuki.DirectedCStarLimit.stage._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_24
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.noConfusion
#print axioms Suzuki.UnitizationRFD.exists_separating_tails
#print axioms Suzuki.DirectedCStarLimit.stage_isometry
#print axioms Suzuki.InductiveAmalgam.System.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.coefficient_map
#print axioms Suzuki.CommonCorner.coe_one
#print axioms Suzuki.MatrixRetractions.entryCP._proof_3
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_9
#print axioms Suzuki.Target.IsPurelyInfinite
#print axioms Suzuki.InductiveAmalgam.System.mk.injEq
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_4
#print axioms Suzuki.CStarCompletion.inclusion
#print axioms Suzuki.MultiplicityEmbeddings.reindex_eq_unitary_conjugation
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv._proof_3
#print axioms Suzuki.UnitizationRFD.Representation.mk.noConfusion
#print axioms Suzuki.CommonCorner.Frame.representation._proof_12
#print axioms Suzuki.CommonCorner.Frame.representation._proof_17
#print axioms Suzuki.CommonCorner.Frame.mk.sizeOf_spec
#print axioms Suzuki.InductiveAmalgam.System.Hom.noConfusionType
#print axioms Suzuki.UnitizationRFD.Representation.mk.inj
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap_contractive
#print axioms Suzuki.CommonCorner.Frame.expand.eq_1
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_3
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm._proof_2
#print axioms Suzuki.PositiveLifting.coordinateEquiv._proof_1
#print axioms Suzuki.CommonCorner.Frame.representation._proof_7
#print axioms Suzuki.CornerFiniteness.complementHom_star
#print axioms Suzuki.CornerPureInfiniteness.hereditary_subset_corner
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift.congr_simp
#print axioms Suzuki.DirectedCStarLimit.algebraicNormedAlgebra._proof_3
#print axioms Suzuki.MatrixRetractions.singleHom_injective
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_4
#print axioms Suzuki.LimitCPMaps.algebraicTopology
#print axioms Suzuki.LimitCPMaps.algebraicMap._proof_5
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap._proof_1
#print axioms Suzuki.MatrixLimits.matrixHom._proof_4
#print axioms Suzuki.LimitCPMaps.cpMap_stage
#print axioms Suzuki.PositiveLifting.exists_compatible_lifts._abel_1_1
#print axioms Suzuki.SimpleFullness.closedIdeal
#print axioms Suzuki.CommonCorner.cornerRing._proof_5
#print axioms Suzuki.CommonCorner.compress._proof_3
#print axioms Suzuki.CommonCorner.coe_star
#print axioms Suzuki.FiniteCPApproximation.TotalMatrix
#print axioms Suzuki.CommonCorner.coe_compress
#print axioms Suzuki.FiniteCPApproximation.cpComp._proof_1
#print axioms Suzuki.DirectedCStarLimit.dense_stage_union
#print axioms Suzuki.DirectedCStarLimit.algebraicNormedRing._proof_1
#print axioms Suzuki.MatrixLimits.limitOrder
#print axioms Suzuki.CommonCorner.Frame.star_support
#print axioms Suzuki.CornerCPApproximation.hasCPApproximation
#print axioms Suzuki.CommonCorner.compress._proof_2
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stage_limitRetraction_of_le
#print axioms Suzuki.CornerPureInfiniteness.isKirchberg
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_1
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_7
#print axioms Suzuki.CommonCorner.cornerNormedRing._proof_2
#print axioms Suzuki.FiniteCPApproximation.blockInclusion._proof_1
#print axioms Suzuki.Target.UnitalAlgebra
#print axioms Suzuki.CommonCorner.map.congr_simp
#print axioms Suzuki.IdempotentSystems.correction.eq_1
#print axioms Suzuki.MultiplicityEmbeddings.card_slots
#print axioms Suzuki.CommonCorner.coe_toCornerHom
#print axioms Suzuki.CStarCompletion.completionStar
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_1
#print axioms Suzuki.InductiveAmalgam.System.ctorIdx
#print axioms Suzuki.CommonCorner.cornerNormedRing._proof_1
#print axioms Suzuki.PositiveLifting.exists_positive_compatible_lifts
#print axioms Suzuki.CornerCPApproximation.nonneg_of_injective_nonunital
#print axioms Suzuki.MultiplicityEmbeddings.copyHom._proof_1
#print axioms Suzuki.FiniteCPApproximation.blockCompression
#print axioms Suzuki.CornerFiniteness.complementHom
#print axioms Suzuki.CommonCorner.map._proof_6
#print axioms Suzuki.CornerCPApproximation.inclusionCP._proof_2
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.closure_adjoin_eq_top
#print axioms Suzuki.CommonCorner.toCornerHom._proof_2
#print axioms Suzuki.CommonCorner.matrix_extension
#print axioms Suzuki.FiniteCPApproximation.nonneg_of_injective_hom
#print axioms Suzuki.FiniteDiagram.HasMultiplicity._proof_1
#print axioms Suzuki.LimitCPMaps.algebraicMap
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.splitLimitAlgebra
#print axioms Suzuki.MultiplicityEmbeddings.secondMultiplicity.congr_simp
#print axioms Suzuki.ResidualRepresentations.separatingTails_detects_equality
#print axioms Suzuki.FiniteDiagram.HasMultiplicity.congr_simp
#print axioms Suzuki.MatrixRetractions.entryCP_apply
#print axioms Suzuki.FiniteDiagram.targetRight
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_5
#print axioms Suzuki.Target.UnitalAlgebra.mk.injEq
#print axioms Suzuki.MatrixLimits.matrixHom._proof_2
#print axioms Suzuki.Target.UnitalAlgebra.algebra
#print axioms Suzuki.CornerFiniteness.corner_separable
#print axioms Suzuki.CStarCompletion.completionCStarAlgebra._proof_1
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk._flat_ctor
#print axioms Suzuki.CornerFiniteness.complementHom_injective
#print axioms Suzuki.CommonCorner.Frame.mk._flat_ctor
#print axioms Suzuki.CommonCorner.cornerRing
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_1
#print axioms Suzuki.FiniteDiagram.Realization.noConfusion
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_4
#print axioms Suzuki.MultiplicityEmbeddings.copies_unitarily_conjugate_of_counts
#print axioms Suzuki.FiniteDiagram.HasMultiplicity._proof_2
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_6
#print axioms Suzuki.CornerPureInfiniteness.mem_hereditary_iff
#print axioms Suzuki.FiniteDiagram.Realization.mk.noConfusion
#print axioms Suzuki.FiniteDiagram.Realization.target_second_isometry
#print axioms Suzuki.LimitCPMaps.continuousMap.congr_simp
#print axioms Suzuki.MultiplicityEmbeddings.second_targetSize
#print axioms Suzuki.PositiveLifting.Positive
#print axioms Suzuki.CornerPureInfiniteness.left_support_of_square
#print axioms Suzuki.CommonCorner.Frame.coefficient_projection
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm._proof_5
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._simp_1_4
#print axioms Suzuki.FiniteDiagram.Realization.mk
#print axioms Suzuki.CommonCorner.Frame.coe_gram_apply
#print axioms Suzuki.CommonCorner.Frame.matrixHom_injective
#print axioms Suzuki.LimitCPMaps.algebraicMap._proof_4
#print axioms Suzuki.IdempotentSystems.correction._f
#print axioms Suzuki.DirectedCStarLimit.algebraicCStarRing
#print axioms Suzuki.Target.UnitalAlgebra.mk
#print axioms Suzuki.InductiveAmalgam.System.casesOn
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_10
#print axioms Suzuki.MatrixRetractions.diagonal_has_cpc_retraction
#print axioms Suzuki.CornerFiniteness.stablyFiniteRing
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.extension
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.limitRetraction
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_2
#print axioms Suzuki.InductiveAmalgam.System.recOn
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_6
#print axioms Suzuki.MultiplicityEmbeddings.composition_copy_count
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_4
#print axioms Suzuki.MatrixLimits.finite_common_stage
#print axioms Suzuki.MatrixRetractions.coordinateEquiv._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom_isometry
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_3
#print axioms Suzuki.FiniteCPApproximation.blockPinching._simp_1_2
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_1
#print axioms Suzuki.MatrixDiagrams.kernel_action._abel_1_2
#print axioms Suzuki.SimpleFullness.exists_frame
#print axioms Suzuki.CStarCompletion.star_coe
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.tendsto_stage_limitRetraction
#print axioms Suzuki.MatrixDiagrams.first_square
#print axioms Suzuki.CommonCorner.Frame.representation._proof_20
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap._f
#print axioms Suzuki.RFDAmplification.matrix_rfd
#print axioms Suzuki.CommonCorner.toCornerHom._proof_11
#print axioms Suzuki.CommonCorner.rowCompression._proof_6
#print axioms Suzuki.CStarCompletion.inclusion_isometry
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_9
#print axioms Suzuki.CommonCorner.map._proof_10
#print axioms Suzuki.FiniteDiagram.Realization.common_isometry
#print axioms Suzuki.Target.UnitalAlgebra._sizeOf_inst
#print axioms Suzuki.CStarCompletion.completionStarRing._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.recOn
#print axioms Suzuki.ResidualRepresentations.Representation._sizeOf_inst
#print axioms Suzuki.FiniteDiagram.Realization.left_multiplicity
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_5
#print axioms Suzuki.FiniteDiagram.Realization.casesOn
#print axioms Suzuki.CommonCorner.Frame.representation._proof_16
#print axioms Suzuki.CornerFiniteness.corner_stablyFiniteRing
#print axioms Suzuki.MultiplicityEmbeddings.exists_isometric_exact_square
#print axioms Suzuki.MultiplicityEmbeddings.copyHom_injective
#print axioms Suzuki.FiniteCPApproximation.blockInclusion._proof_5
#print axioms Suzuki.MatrixLimits.matrixHom._proof_5
#print axioms Suzuki.MatrixRetractions.coordinate_sandwich
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_2
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.retract
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_14
#print axioms Suzuki.MatrixLimits.matrixDedekindFinite
#print axioms Suzuki.CStarCompletion.completionStarRing._proof_3
#print axioms Suzuki.MatrixLimits.matrixHom_injective
#print axioms Suzuki.Target.IsInfiniteProjection
#print axioms Suzuki.MatrixRetractions.singleHom._proof_4
#print axioms Suzuki.FiniteCPApproximation.blockPinching
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.eq_top_of_isClosed
#print axioms Suzuki.FiniteDiagram.Realization.first_square
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_4
#print axioms Suzuki.Target.instPartialOrderCarrier
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_7
#print axioms Suzuki.CommonCorner.Frame.coefficient_add
#print axioms Suzuki.CStarCompletion.completionNormedAlgebra._proof_4
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_2
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_1
#print axioms Suzuki.Target.HasFiniteAmalgam
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra
#print axioms Suzuki.CStarCompletion.completionNormedAlgebra._proof_1
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_5
#print axioms Suzuki.SimpleTraces.mem_nullIdeal
#print axioms Suzuki.UnitizationRFD.Representation._sizeOf_1
#print axioms Suzuki.CommonCorner.FullProjection.exists_strictlyPositive_sum
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.commutes
#print axioms Suzuki.ResidualRepresentations.Representation.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_3
#print axioms Suzuki.CommonCorner.cornerRing._proof_25
#print axioms Suzuki.CommonCorner.Frame.amplification
#print axioms Suzuki.FiniteDiagram.natMatrix_cast
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_2
#print axioms Suzuki.ResidualRepresentations.Representation.rec
#print axioms Suzuki.FiniteDiagram.Realization._sizeOf_1
#print axioms Suzuki.InductiveAmalgam.System.Hom.ctorIdx
#print axioms Suzuki.MultiplicityEmbeddings.slotEquiv
#print axioms Suzuki.CStarCompletion.completionCStarAlgebra
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_1
#print axioms Suzuki.CommonCorner.Frame.expand
#print axioms Suzuki.MatrixRetractions.coordinateProjection_isProjection
#print axioms Suzuki.CommonCorner.inclusion
#print axioms Suzuki.CommonCorner.Frame.mk.noConfusion
#print axioms Suzuki.CornerFiniteness.complementHom.eq_1
#print axioms Suzuki.MatrixDiagrams.second_square._abel_1_2
#print axioms Suzuki.LimitCPMaps.matrixMap_nonneg
#print axioms Suzuki.SequentialCStarLimit.Limit
#print axioms Suzuki.UnitizationRFD.extend._proof_5
#print axioms Suzuki.CStarCompletion.inclusion._proof_3
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.limitOrder
#print axioms Suzuki.FiniteCPApproximation.blockProjection_isProjection
#print axioms Suzuki.DirectedCStarLimit.stageNorm._proof_1
#print axioms Suzuki.CStarCompletion.lift._proof_5
#print axioms Suzuki.CPApproximationLimits.CPCSplitting
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.rec
#print axioms Suzuki.CommonCorner.map
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_right
#print axioms Suzuki.CommonCorner.map._proof_16
#print axioms Suzuki.SequentialCStarLimit.transition_succ
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.hasCPApproximation
#print axioms Suzuki.MatrixLimits.matrixHom._proof_7
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_6
#print axioms Suzuki.MultiplicityEmbeddings.permutationUnitary._simp_1
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_1
#print axioms Suzuki.CommonCorner.isFullAmalgam_of_fullProjection
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_8
#print axioms Suzuki.ResidualRepresentations.exists_separating_sequence
#print axioms Suzuki.CommonCorner.Frame.mk
#print axioms Suzuki.CommonCorner.Corner
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span._simp_1_3
#print axioms Suzuki.CommonCorner.Frame.mapFrame.congr_simp
#print axioms Suzuki.FiniteCPApproximation.hasCPApproximation_iff_of_equiv
#print axioms Suzuki.DirectedCStarLimit.limitCStarAlgebra
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift.congr_simp
#print axioms Suzuki.CommonCorner.Frame.coefficient._simp_1
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_1
#print axioms Suzuki.CornerFiniteness.matrixMap._proof_2
#print axioms Suzuki.CornerCPApproximation.compressionCP
#print axioms Suzuki.MatrixRetractions.singleHom._proof_5
#print axioms Suzuki.CornerFiniteness.matrixMap
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_2
#print axioms Suzuki.ResidualRepresentations.of_injective
#print axioms Suzuki.CommonCorner.ofSupport
#print axioms Suzuki.CommonCorner.Frame.equivalence._proof_1
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra
#print axioms Suzuki.MatrixRetractions.singleHom._proof_3
#print axioms Suzuki.StableFiniteness.FaithfulTrace.casesOn
#print axioms Suzuki.FiniteCPApproximation.hasCPApproximation_of_equiv
#print axioms Suzuki.StableFiniteness.IsStablyFinite
#print axioms Suzuki.MatrixLimits.matrixHom._proof_6
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_3
#print axioms Suzuki.CStarCompletion.completionStarRing._proof_5
#print axioms Suzuki.ResidualRepresentations.Representation.mk.sizeOf_spec
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv._proof_1
#print axioms Suzuki.CommonCorner.cornerClosed
#print axioms Suzuki.CommonCorner.isFullAmalgam_of_frame
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.ctorIdx
#print axioms Suzuki.CommonCorner.map._proof_17
#print axioms Suzuki.CommonCorner.right_support
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_7
#print axioms Suzuki.Target.UnitalAlgebra.rec
#print axioms Suzuki.DirectedCStarLimit.limitCStarAlgebra._proof_1
#print axioms Suzuki.CommonCorner.Frame.eq_top_of_coefficients
#print axioms Suzuki.FiniteDiagram.HasMultiplicity.dimensions
#print axioms Suzuki.MatrixDiagrams.kernel_action._abel_1_3
#print axioms Suzuki.LimitCPMaps.algebraicMap._proof_3
#print axioms Suzuki.MatrixRetractions.diagonalHom._proof_3
#print axioms Suzuki.Target.IsFiniteConstituent
#print axioms Suzuki.OrthogonalChannels.compression
#print axioms Suzuki.CommonCorner.Frame.coefficient
#print axioms Suzuki.InductiveAmalgam.System.Hom
#print axioms Suzuki.FiniteCPApproximation.cpZero_apply
#print axioms Suzuki.CommonCorner.Frame.total
#print axioms Suzuki.DirectedCStarLimit.algebraicSeparable
#print axioms Suzuki.CornerCPApproximation.compressionCP._proof_1
#print axioms Suzuki.FiniteCPApproximation.blockInclusion_injective
#print axioms Suzuki.ResidualRepresentations.Representation.mk.injEq
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_2
#print axioms Suzuki.CommonCorner.Frame.coe_coefficient
#print axioms Suzuki.LimitCPMaps.continuousMap_coe
#print axioms Suzuki.Target.UnitalAlgebra.mk.sizeOf_spec
#print axioms Suzuki.FiniteDiagram.simultaneous_realizations
#print axioms Suzuki.CommonCorner.Frame.coefficient_star
#print axioms Suzuki.DirectedCStarLimit.Algebraic
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.copyHom._proof_4
#print axioms Suzuki.MatrixRetractions.diagonalHom._proof_1
#print axioms Suzuki.SequentialCStarLimit.limitCStarAlgebra
#print axioms Suzuki.StableFiniteness.FaithfulTrace.rec
#print axioms Suzuki.InductiveAmalgam.System.Hom.rec
#print axioms Suzuki.CommonCorner.Frame._sizeOf_inst
#print axioms Suzuki.UnitizationRFD.extend._proof_2
#print axioms Suzuki.UnitizationRFD.extend._proof_3
#print axioms Suzuki.SequentialCStarLimit.stage_commutes
#print axioms Suzuki.CStarCompletion.completionStarModule
#print axioms Suzuki.FiniteDiagram.natMatrix_positive._proof_1_1
#print axioms Suzuki.CommonCorner.cornerAlgebra._proof_2
#print axioms Suzuki.MultiplicityEmbeddings.secondMultiplicity
#print axioms Suzuki.DirectedCStarLimit.algebraicStage_apply
#print axioms Suzuki.MatrixRetractions.entryCP_contractive
#print axioms Suzuki.DirectedCStarLimit.algebraicLift_mk
#print axioms Suzuki.FiniteDiagram.Realization.rec
#print axioms Suzuki.CStarCompletion.lift._proof_3
#print axioms Suzuki.CStarCompletion.lift._proof_4
#print axioms Suzuki.FiniteCPApproximation.homCP_apply
#print axioms Suzuki.FiniteDiagram.Realization.left
#print axioms Suzuki.DirectedCStarLimit.algebraicLift_contractive
#print axioms Suzuki.PositiveLifting.kernel_left_unimodular
#print axioms Suzuki.FiniteCPApproximation.blockInclusion._proof_4
#print axioms Suzuki.DirectedCStarLimit.stage._proof_3
#print axioms Suzuki.UnitizationRFD.Representation.ctorIdx
#print axioms Suzuki.CommonCorner.Frame.noConfusion
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.recOn
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom._proof_4
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv_stage
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy
#print axioms Suzuki.FiniteDiagram.exact_square_with_multiplicity
#print axioms Suzuki.InductiveAmalgam.System.mk.inj
#print axioms Suzuki.UnitizationRFD.Representation._sizeOf_inst
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap.eq_def
#print axioms Suzuki.IdempotentSystems.correction._sunfold
#print axioms Suzuki.LimitCPMaps.algebraicContinuousMap._proof_1
#print axioms Suzuki.CommonCorner.Frame.representation._proof_10
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.limitRetraction_stage
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_5
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_7
#print axioms Suzuki.FiniteDiagram.Realization.right_isometry
#print axioms Suzuki.UnitizationRFD.Representation.mk
#print axioms Suzuki.SequentialCStarLimit.stage.eq_1
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.compositionDimensionEq
#print axioms Suzuki.CommonCorner.Frame.coefficient_smul
#print axioms Suzuki.CommonCorner.Frame.mapFrame._proof_1
#print axioms Suzuki.LimitCPMaps.continuousMap
#print axioms Suzuki.FiniteCPApproximation.blockCompressionCP._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.eq_top_of_isClosed
#print axioms Suzuki.InductiveAmalgam.System
#print axioms Suzuki.CommonCorner.Frame.recOn
#print axioms Suzuki.SequentialCStarLimit.map_isometry
#print axioms Suzuki.MatrixDiagrams.first_square._abel_1_2
#print axioms Suzuki.CPApproximationLimits.CPCSplitting._sizeOf_inst
#print axioms Suzuki.CornerPureInfiniteness.isPurelyInfinite
#print axioms Suzuki.MultiplicityEmbeddings.copyHom._proof_2
#print axioms Suzuki.CommonCorner.Frame.matrixHom_expand
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom_copy
#print axioms Suzuki.MultiplicityEmbeddings.copyHom_different
#print axioms Suzuki.CommonCorner.map._proof_8
#print axioms Suzuki.CommonCorner.cornerRing._proof_12
#print axioms Suzuki.CommonCorner.Frame.equivalence._proof_3
#print axioms Suzuki.SimpleTraces.stablyFinite
#print axioms Suzuki.CPApproximationLimits.stageOrder
#print axioms Suzuki.InductiveAmalgam.System.noConfusionType
#print axioms Suzuki.MatrixRetractions.coordinateProjection
#print axioms Suzuki.FiniteCPApproximation.homCP._proof_1
#print axioms Suzuki.MatrixDiagrams.diagram.eq_1
#print axioms Suzuki.DirectedCStarLimit.stage._proof_4
#print axioms Suzuki.UnitizationRFD.Representation.noConfusion
#print axioms Suzuki.FiniteDiagram.natural_second_square
#print axioms Suzuki.FiniteDiagram.identity_nonnegative._proof_1_2
#print axioms Suzuki.CommonCorner.Frame.ofApproximation
#print axioms Suzuki.UnitizationRFD.extend._proof_4
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.injEq
#print axioms Suzuki.DirectedCStarLimit.algebraicNormedAlgebra
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom_pullback
#print axioms Suzuki.PositiveLifting.Cokernel
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap
#print axioms Suzuki.CommonCorner.rowCompression._proof_3
#print axioms Suzuki.LimitCPMaps.continuousMap._proof_7
#print axioms Suzuki.CornerCPApproximation.inclusionCP._proof_3
#print axioms Suzuki.SimpleTraces.nullIdeal_isClosed
#print axioms Suzuki.InductiveAmalgam.System.mk.noConfusion
#print axioms Suzuki.MultiplicityEmbeddings.firstMultiplicity.congr_simp
#print axioms Suzuki.CornerFiniteness.dedekindFinite
#print axioms Suzuki.SequentialCStarLimit.limitSeparable
#print axioms Suzuki.CommonCorner.toCornerHom._proof_8
#print axioms Suzuki.CommonCorner.strictlyPositive_sum_of_factorization
#print axioms Suzuki.CommonCorner.Frame.representation._proof_1
#print axioms Suzuki.SimpleFullness.full_of_nonzero
#print axioms Suzuki.FiniteCPApproximation.blockCompressionCP._proof_2
#print axioms Suzuki.UnitizationRFD.Representation.mk.sizeOf_spec
#print axioms Suzuki.MultiplicityEmbeddings.positive_integer_multiplicity_isometry._proof_1_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift
#print axioms Suzuki.LimitCPMaps.stageOrderedRing
#print axioms Suzuki.StableFiniteness.FaithfulTrace.toAddMonoidHom
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.limitOrderedRing
#print axioms Suzuki.CommonCorner.map._proof_12
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift_comp_lift
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_4
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_10
#print axioms Suzuki.CStarCompletion.completionStarRing._simp_1
#print axioms Suzuki.CommonCorner.cornerRing._aux_13
#print axioms Suzuki.ResidualRepresentations.exists_separating_tails
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_3
#print axioms Suzuki.CommonCorner.Frame.casesOn
#print axioms Suzuki.CommonCorner.compress._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_17
#print axioms Suzuki.PositiveLifting.quotient
#print axioms Suzuki.LimitCPMaps.continuousMap_contractive
#print axioms Suzuki.DirectedCStarLimit.Limit
#print axioms Suzuki.CornerFiniteness.corner_stablyFinite
#print axioms Suzuki.CornerFiniteness.isometry_unitary
#print axioms Suzuki.CommonCorner.cornerRing._proof_21
#print axioms Suzuki.MultiplicityEmbeddings.copyHom._proof_3
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.mk._flat_ctor
#print axioms Suzuki.MatrixRetractions.diagonalHom._proof_5
#print axioms Suzuki.UnitizationRFD.augmentation._proof_1
#print axioms Suzuki.CStarCompletion.inclusion._proof_1
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm._proof_4
#print axioms Suzuki.Target.MainClaim
#print axioms Suzuki.InductiveAmalgam.System.mk.sizeOf_spec
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_3
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.commutes
#print axioms Suzuki.CommonCorner.Frame.rec
#print axioms Suzuki.CommonCorner.FullProjection.exists_frame
#print axioms Suzuki.LimitCPMaps.matrixMap_square_nonneg
#print axioms Suzuki.MatrixLimits.isStablyFiniteRing
#print axioms Suzuki.FiniteCPApproximation.blockInclusion._proof_3
#print axioms Suzuki.MatrixRetractions.singleHom._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_15
#print axioms Suzuki.UnitizationRFD.augmentation._proof_2
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom_isometry_of_positive
#print axioms Suzuki.OrthogonalChannels.cross_mul
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_6
#print axioms Suzuki.SequentialCStarLimit.transition_injective
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.casesOn
#print axioms Suzuki.CommonCorner.inclusion_isometry
#print axioms Suzuki.PositiveLifting.Cokernel._proof_1
#print axioms Suzuki.CommonCorner.fullProjection_iff_exists_frame
#print axioms Suzuki.MultiplicityEmbeddings.composition_copy
#print axioms Suzuki.CommonCorner.Frame.mapFrame._proof_2
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.casesOn
#print axioms Suzuki.StableFiniteness.matrixTrace.eq_1
#print axioms Suzuki.IdempotentSystems.correction
#print axioms Suzuki.CommonCorner.cornerSubalgebra._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.compositionLabel
#print axioms Suzuki.CommonCorner.cornerSubalgebra._proof_2
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.rec
#print axioms Suzuki.CommonCorner.toCornerHom._proof_9
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv._proof_2
#print axioms Suzuki.FiniteDiagram.Realization.left_dimensions
#print axioms Suzuki.Target.UnitalAlgebra.mk._flat_ctor
#print axioms Suzuki.DirectedCStarLimit.algebraicLift._proof_1
#print axioms Suzuki.CStarCompletion.completionStarRing._simp_2
#print axioms Suzuki.LimitCPMaps.matrixMap_continuous
#print axioms Suzuki.CornerCPApproximation.inclusionCP
#print axioms Suzuki.LimitCPMaps.limitOrder
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift
#print axioms Suzuki.FiniteDiagram.PositiveDimensions
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_7
#print axioms Suzuki.CornerFiniteness.stablyFinite
#print axioms Suzuki.CStarCompletion.inclusion_denseRange
#print axioms Suzuki.CornerSimplicity.ideals_trivial
#print axioms Suzuki.CommonCorner.cornerRing._aux_22
#print axioms Suzuki.ResidualRepresentations.IsRFD
#print axioms Suzuki.MultiplicityEmbeddings.CopySlots
#print axioms Suzuki.CommonCorner.map._proof_1
#print axioms Suzuki.InductiveAmalgam.isFullAmalgam_of_colimits
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.retraction_error_le
#print axioms Suzuki.SimpleTraces.nullIdeal.congr_simp
#print axioms Suzuki.IdempotentSystems.compatible_iff_constant_fixed
#print axioms Suzuki.FiniteCPApproximation.amplifyHom._proof_4
#print axioms Suzuki.FiniteCPApproximation.finiteProduct_hasCPApproximation
#print axioms Suzuki.MultiplicityEmbeddings.permutationUnitary
#print axioms Suzuki.UnitizationRFD.Representation.mk.injEq
#print axioms Suzuki.Target.UnitalAlgebra.ctorIdx
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap_of_le
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.injEq
#print axioms Suzuki.CommonCorner.Frame.coefficient._proof_1
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span._simp_1_1
#print axioms Suzuki.CStarCompletion.completionNormedAlgebra
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_2
#print axioms Suzuki.FiniteDiagram.Realization.source_first_isometry
#print axioms Suzuki.CommonCorner.Frame.representation_surjective
#print axioms Suzuki.FiniteDiagram.natural_realization
#print axioms Suzuki.FiniteDiagram.natMatrix_product_eq
#print axioms Suzuki.DirectedCStarLimit.algebraicStage_isometry
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_4
#print axioms Suzuki.CommonCorner.Frame.gram
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_2
#print axioms Suzuki.LimitFiniteness.dedekindFinite
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom._proof_6
#print axioms Suzuki.FiniteCPApproximation.blockCompression._proof_2
#print axioms Suzuki.CommonCorner.cornerRing._proof_17
#print axioms Suzuki.MultiplicityEmbeddings.copyHom
#print axioms Suzuki.CommonCorner.corner_eq_top_of_isClosed
#print axioms Suzuki.CommonCorner.Frame.mk.inj
#print axioms Suzuki.CStarCompletion.lift._proof_6
#print axioms Suzuki.CommonCorner.Frame.ofApproximation._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.rec
#print axioms Suzuki.MatrixRetractions.entryCP._proof_2
#print axioms Suzuki.FiniteDiagram.all_dimensions_positive
#print axioms Suzuki.SimpleTraces.null_right
#print axioms Suzuki.FiniteCPApproximation.blockInclusion_norm
#print axioms Suzuki.DirectedCStarLimit.algebraicStage
#print axioms Suzuki.Target.UnitalAlgebra.casesOn
#print axioms Suzuki.FiniteDiagram.commonMap
#print axioms Suzuki.CornerFiniteness.complementHom._abel_1
#print axioms Suzuki.LimitCPMaps.cpMap
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.noConfusion
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.map_stage
#print axioms Suzuki.MatrixLimits.matrixHom._proof_3
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_4
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_5
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift_unique
#print axioms Suzuki.PositiveLifting.exists_large_unimodular
#print axioms Suzuki.FiniteDiagram.Realization.source_second_isometry
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv_isometry
#print axioms Suzuki.CommonCorner.cornerRing._proof_19
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._simp_1
#print axioms Suzuki.FiniteCPApproximation.blockInclusion
#print axioms Suzuki.UnitizationRFD.augmentation
#print axioms Suzuki.MatrixDiagrams.adjusted_kernel
#print axioms Suzuki.SequentialCStarLimit.transition
#print axioms Suzuki.UnitizationRFD.Representation.dimension
#print axioms Suzuki.StableFiniteness.FaithfulTrace
#print axioms Suzuki.LimitFiniteness.dense_stage_pairs
#print axioms Suzuki.InductiveAmalgam.System._sizeOf_inst
#print axioms Suzuki.StableFiniteness.matrixTrace_faithful
#print axioms Suzuki.SequentialCStarLimit.norm_stage
#print axioms Suzuki.InductiveAmalgam.System.Hom.naturality
#print axioms Suzuki.StableFiniteness.amplification
#print axioms Suzuki.FiniteCornerAmalgam.cornerMap_injective
#print axioms Suzuki.TracialFunctional.stablyFinite
#print axioms Suzuki.FiniteCPApproximation.blockCompression._proof_1
#print axioms Suzuki.StableFiniteness.matrixTrace
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap._sunfold
#print axioms Suzuki.SimpleTraces.nullIdeal.eq_1
#print axioms Suzuki.FiniteCPApproximation.blockProjection
#print axioms Suzuki.CommonCorner.cornerNormedAlgebra
#print axioms Suzuki.CommonCorner.Frame.noConfusionType
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_8
#print axioms Suzuki.RFDAmplification.representation
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.mk.injEq
#print axioms Suzuki.MultiplicityEmbeddings.Copies
#print axioms Suzuki.StableFiniteness.faithful_trace_stablyFinite
#print axioms Suzuki.CommonCorner.Frame.representation._proof_2
#print axioms Suzuki.RFDAmplification.flatten
#print axioms Suzuki.InductiveAmalgam.System.obj
#print axioms Suzuki.RFDAmplification.representation._proof_1
#print axioms Suzuki.MatrixLimits.matrixHom._proof_1
#print axioms Suzuki.MultiplicityEmbeddings.secondMultiplicity.eq_1
#print axioms Suzuki.SequentialCStarLimit.transition.congr_simp
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.map
#print axioms Suzuki.CPApproximationLimits.stageOrderedRing
#print axioms Suzuki.OrthogonalChannels.cross_mul._simp_1_1
#print axioms Suzuki.CommonCorner.Frame.equivalence._proof_2
#print axioms Suzuki.MultiplicityEmbeddings.composition_normalForm
#print axioms Suzuki.InductiveAmalgam.System._sizeOf_1
#print axioms Suzuki.UnitizationRFD.Representation.positive_dimension
#print axioms Suzuki.FiniteCPApproximation.blocks_hasCPApproximation
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_9
#print axioms Suzuki.FiniteCPApproximation.matrix_sum_entry
#print axioms Suzuki.CommonCorner.Frame.coefficient_injective
#print axioms Suzuki.CommonCorner.Frame.representation_injective
#print axioms Suzuki.SequentialCStarLimit.transitionDirectedSystem
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_5
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_2
#print axioms Suzuki.CornerCPApproximation.compressionCP_apply
#print axioms Suzuki.UnitizationRFD.unitization_rfd
#print axioms Suzuki.DirectedCStarLimit.algebraicRingNorm._proof_1
#print axioms Suzuki.CommonCorner.compress_coe
#print axioms Suzuki.CommonCorner.Frame.corner_reconstruction
#print axioms Suzuki.FiniteDiagram.target_dimensions_positive
#print axioms Suzuki.OrthogonalChannels.sumHom_injective
#print axioms Suzuki.CommonCorner.Frame.representation
#print axioms Suzuki.MatrixRetractions.entryCP
#print axioms Suzuki.CommonCorner.rowCompression._proof_2
#print axioms Suzuki.FiniteCPApproximation.blocksAlgebra
#print axioms Suzuki.CommonCorner.toCornerHom._proof_19
#print axioms Suzuki.LimitCPMaps.algebraicMap_stage
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_5
#print axioms Suzuki.MultiplicityEmbeddings.permutationUnitary._proof_1
#print axioms Suzuki.CommonCorner.Frame.mapFrame
#print axioms Suzuki.MatrixDiagrams.kernel_action
#print axioms Suzuki.StableFiniteness.matrixTrace_cyclic
#print axioms Suzuki.CommonCorner.map._proof_2
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.inj
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_7
#print axioms Suzuki.ResidualRepresentations.isStablyFiniteRing
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap.eq_2
#print axioms Suzuki.MultiplicityEmbeddings.secondInclusion
#print axioms Suzuki.ResidualRepresentations.Representation.noConfusionType
#print axioms Suzuki.FiniteDiagram.natural_first_square
#print axioms Suzuki.DirectedCStarLimit.algebraicLift
#print axioms Suzuki.FiniteDiagram.targetLeft
#print axioms Suzuki.MatrixDiagrams.adjusted_chain
#print axioms Suzuki.InductiveAmalgam.System.Hom.casesOn
#print axioms Suzuki.Target.HasCPApproximation._proof_1
#print axioms Suzuki.FiniteDiagram.Realization._sizeOf_inst
#print axioms Suzuki.UnitizationRFD.Representation.hom
#print axioms Suzuki.FiniteCPApproximation.hasCPApproximation_of_subsingleton
#print axioms Suzuki.FiniteCPApproximation.blockProjection.congr_simp
#print axioms Suzuki.SimpleTraces.nullIdeal._proof_2
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_6
#print axioms Suzuki.FiniteDiagram.Realization.recOn
#print axioms Suzuki.FiniteCPApproximation.blockCompression_contract
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv._proof_2
#print axioms Suzuki.LimitCPMaps.algebraicContinuousMap
#print axioms Suzuki.MultiplicityEmbeddings.multiplicityHom
#print axioms Suzuki.ResidualRepresentations.Representation.recOn
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv_right
#print axioms Suzuki.MultiplicityEmbeddings.exists_copy_reindex_of_label_equiv
#print axioms Suzuki.FiniteDiagram.Realization.mk._flat_ctor
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.inj
#print axioms Suzuki.IdempotentSystems.one_sub_shift_surjective._abel_1_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.closure_adjoin_eq_top
#print axioms Suzuki.FiniteDiagram.natMatrix_second
#print axioms Suzuki.CommonCorner.coe_sum
#print axioms Suzuki.UnitizationRFD.Representation.noConfusionType
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.mk._flat_ctor
#print axioms Suzuki.SimpleTraces.nullIdeal
#print axioms Suzuki.CornerFiniteness.corner_stablyFinite_of
#print axioms Suzuki.CommonCorner.compress._proof_5
#print axioms Suzuki.CommonCorner.cornerRing._proof_10
#print axioms Suzuki.CStarCompletion.completionStarRing._proof_2
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.noConfusionType
#print axioms Suzuki.MultiplicityEmbeddings.Slots
#print axioms Suzuki.CommonCorner.Frame.representation._proof_15
#print axioms Suzuki.MultiplicityEmbeddings.rowHom
#print axioms Suzuki.CommonCorner.toCornerHom._proof_7
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_5
#print axioms Suzuki.FiniteCPApproximation.blockCompressionCP
#print axioms Suzuki.FiniteDiagram.Realization.second_square
#print axioms Suzuki.DirectedCStarLimit.algebraicNormedAlgebra._proof_2
#print axioms Suzuki.FiniteCornerAmalgam.hasFiniteAmalgam
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_8
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.stageMap_step
#print axioms Suzuki.IdempotentSystems.correction.match_1
#print axioms Suzuki.IdempotentSystems.correction_fixed
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_5
#print axioms Suzuki.FiniteCPApproximation.cpZero
#print axioms Suzuki.CommonCorner.Frame.equivalence
#print axioms Suzuki.CommonCorner.cornerNormedRing
#print axioms Suzuki.FiniteCPApproximation.cpComp
#print axioms Suzuki.CStarCompletion.completionNormedAlgebra._proof_3
#print axioms Suzuki.UnitizationRFD.scalarRepresentation
#print axioms Suzuki.CPApproximationLimits.CPCSplitting.contractive
#print axioms Suzuki.LimitCPMaps.stageOrder
#print axioms Suzuki.CommonCorner.toCornerHom._proof_3
#print axioms Suzuki.TracialFunctional.toFaithfulTrace
#print axioms Suzuki.CommonCorner.Frame.representation._proof_6
#print axioms Suzuki.SimpleTraces.null_iff_norm
#print axioms Suzuki.CommonCorner.rowCompression._proof_4
#print axioms Suzuki.SequentialCStarLimit.isSequentialColimit
#print axioms Suzuki.CommonCorner.Frame.representation._proof_3
#print axioms Suzuki.CStarCompletion.lift_unique
#print axioms Suzuki.LimitFiniteness.of_dense_pairs
#print axioms Suzuki.ResidualRepresentations.Representation.hom
