import Suzuki

-- This exact-version audit intentionally names generated auxiliary declarations.
-- Suppress only the warning against referencing such names across refactors.
set_option linter.auxLemma false

-- Every compiled declaration in the Suzuki namespace, including generated ones.
#print axioms Suzuki.CommonCorner.Frame.gram_projection
#print axioms Suzuki.PositiveLifting.Kernel
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra_closed
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.hom_ext
#print axioms Suzuki.CommonCorner.corner_hom_ext
#print axioms Suzuki.CommonCorner.Frame.mk.injEq
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv
#print axioms Suzuki.InductiveAmalgam.System.algebra
#print axioms Suzuki.InductiveAmalgam.System.Hom._sizeOf_inst
#print axioms Suzuki.CommonCorner.toCornerHom._proof_4
#print axioms Suzuki.CommonCorner.cornerPartialOrder
#print axioms Suzuki.CommonCorner.rowCompression._proof_1
#print axioms Suzuki.InductiveAmalgam.System.mk
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv_left
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_2
#print axioms Suzuki.CommonCorner.inclusion_apply
#print axioms Suzuki.CommonCorner.Frame
#print axioms Suzuki.CommonCorner.Frame.representation._proof_8
#print axioms Suzuki.CommonCorner.compress._proof_4
#print axioms Suzuki.CommonCorner.Frame.representation._proof_13
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_16
#print axioms Suzuki.CommonCorner.Frame.representation._proof_4
#print axioms Suzuki.CommonCorner.Frame.matrixHom
#print axioms Suzuki.PositiveLifting.row_sum_le_mul
#print axioms Suzuki.Target.UnitalAlgebra._sizeOf_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_20
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_1
#print axioms Suzuki.Target.HasCPApproximation
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv._proof_3
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_2
#print axioms Suzuki.SimpleTraces.faithful_of_simple
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift_stage
#print axioms Suzuki.PositiveLifting.coordinateEquiv
#print axioms Suzuki.CommonCorner.map._proof_3
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.casesOn
#print axioms Suzuki.CommonCorner.rowCompression._proof_5
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv_isometry
#print axioms Suzuki.CommonCorner.cornerRing._aux_5
#print axioms Suzuki.MatrixDiagrams.first_square._abel_1_3
#print axioms Suzuki.CommonCorner.map._proof_14
#print axioms Suzuki.CommonCorner.Frame.ofApproximation._proof_2
#print axioms Suzuki.InductiveAmalgam.System.Hom._sizeOf_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_1
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_10
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.mk
#print axioms Suzuki.PositiveLifting.homotopy_cokernel
#print axioms Suzuki.StableFiniteness.FaithfulTrace.nonnegative
#print axioms Suzuki.StableFiniteness.amplification._proof_2
#print axioms Suzuki.CommonCorner.ofSupport._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_comp_lift
#print axioms Suzuki.InductiveAmalgam.System.noConfusion
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting
#print axioms Suzuki.StableFiniteness.FaithfulTrace.recOn
#print axioms Suzuki.CommonCorner.coe_ofSupport
#print axioms Suzuki.CommonCorner.Frame.fullProjection
#print axioms Suzuki.CommonCorner.map._proof_4
#print axioms Suzuki.SimpleTraces.null_left
#print axioms Suzuki.CommonCorner.toCornerHom
#print axioms Suzuki.CommonCorner.Frame.support
#print axioms Suzuki.InductiveAmalgam.isFullAmalgam_canonical
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_3
#print axioms Suzuki.CommonCorner.cornerRing._aux_1
#print axioms Suzuki.Target.UnitalAlgebra.mk.noConfusion
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.mk
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.sizeOf_spec
#print axioms Suzuki.CommonCorner.cornerSubalgebra
#print axioms Suzuki.CommonCorner.map._proof_18
#print axioms Suzuki.CommonCorner.map._proof_13
#print axioms Suzuki.PositiveLifting.exists_compatible_lifts
#print axioms Suzuki.StableFiniteness.FaithfulTrace.noConfusion
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk
#print axioms Suzuki.SimpleTraces.nullIdeal._proof_1
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_5
#print axioms Suzuki.InductiveAmalgam.System.Hom.recOn
#print axioms Suzuki.Target.instCoeSortUnitalAlgebraType
#print axioms Suzuki.CommonCorner.toCornerHom._proof_13
#print axioms Suzuki.CommonCorner.image_one_projection
#print axioms Suzuki.Target.UnitalAlgebra.noConfusionType
#print axioms Suzuki.Target.UnitalAlgebra.noConfusion
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_6
#print axioms Suzuki.OrthogonalChannels.sumHom
#print axioms Suzuki.CommonCorner.Frame.representation._proof_11
#print axioms Suzuki.CommonCorner.map._proof_19
#print axioms Suzuki.CommonCorner.Frame.representation._proof_14
#print axioms Suzuki.Target.hereditarySet
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_left
#print axioms Suzuki.CommonCorner.toCornerHom._proof_12
#print axioms Suzuki.StableFiniteness.isometry_unitary._abel_1_1
#print axioms Suzuki.SimpleFullness.closedIdeal_isClosed
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span
#print axioms Suzuki.CommonCorner.Frame.equivalence_isometry
#print axioms Suzuki.StableFiniteness.FaithfulTrace.faithful
#print axioms Suzuki.Target.UnitalAlgebra.recOn
#print axioms Suzuki.CommonCorner.map._proof_15
#print axioms Suzuki.StableFiniteness.isometry_unitary
#print axioms Suzuki.StableFiniteness.FaithfulTrace._sizeOf_inst
#print axioms Suzuki.CommonCorner.Frame.coefficient_mul
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_3
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv._proof_1
#print axioms Suzuki.CommonCorner.Frame.representation._proof_21
#print axioms Suzuki.CommonCorner.Frame.coefficient._proof_2
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_11
#print axioms Suzuki.CommonCorner.map_compress
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_3
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.recOn
#print axioms Suzuki.InductiveAmalgam.System.Hom.app
#print axioms Suzuki.CommonCorner.toCornerHom._proof_10
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv_quotient
#print axioms Suzuki.CommonCorner.left_support
#print axioms Suzuki.CommonCorner.Frame.coefficient_continuous
#print axioms Suzuki.CommonCorner.map._proof_11
#print axioms Suzuki.InductiveAmalgam.limit_commutes
#print axioms Suzuki.CommonCorner.cornerStarOrderedRing
#print axioms Suzuki.PositiveLifting.finite_simultaneous_positive_lifting
#print axioms Suzuki.CommonCorner.Frame.amplification_apply
#print axioms Suzuki.SimpleTraces.null_star
#print axioms Suzuki.CommonCorner.cornerRing._proof_3
#print axioms Suzuki.StableFiniteness.amplification._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_16
#print axioms Suzuki.CommonCorner.cornerAlgebra._proof_1
#print axioms Suzuki.Target.UnitalAlgebra.Carrier
#print axioms Suzuki.CommonCorner.map._proof_20
#print axioms Suzuki.CommonCorner.map._proof_7
#print axioms Suzuki.CommonCorner.toCornerHom._proof_18
#print axioms Suzuki.CommonCorner.Frame.ctorIdx
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_8
#print axioms Suzuki.CommonCorner.toCornerHom._proof_5
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra
#print axioms Suzuki.CommonCorner.Frame.compressed_total
#print axioms Suzuki.CommonCorner.toCornerHom._proof_6
#print axioms Suzuki.CommonCorner.cornerRing._proof_4
#print axioms Suzuki.CommonCorner.Frame.x
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_unique
#print axioms Suzuki.CommonCorner.map._proof_5
#print axioms Suzuki.CommonCorner.Frame._sizeOf_1
#print axioms Suzuki.Target.IsKirchberg
#print axioms Suzuki.CommonCorner.Frame.representation._proof_19
#print axioms Suzuki.OrthogonalChannels.sumHom._simp_1
#print axioms Suzuki.MatrixDiagrams.second_square
#print axioms Suzuki.StableFiniteness.FaithfulTrace.cyclic
#print axioms Suzuki.CommonCorner.map._proof_9
#print axioms Suzuki.CommonCorner.Frame.insert
#print axioms Suzuki.CommonCorner.Frame.representation._proof_18
#print axioms Suzuki.CommonCorner.cornerRing._proof_7
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_3
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_9
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span._simp_1_2
#print axioms Suzuki.StableFiniteness.FaithfulTrace._sizeOf_1
#print axioms Suzuki.CommonCorner.coe_mul
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.hom_ext
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_5
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_3
#print axioms Suzuki.CommonCorner.coe_map
#print axioms Suzuki.CommonCorner.Frame.representation._proof_5
#print axioms Suzuki.SimpleTraces.null_add
#print axioms Suzuki.StableFiniteness.FaithfulTrace.noConfusionType
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.map._proof_1
#print axioms Suzuki.CommonCorner.Frame.reconstruction
#print axioms Suzuki.CommonCorner.cornerRing._proof_8
#print axioms Suzuki.CommonCorner.FullProjection
#print axioms Suzuki.CommonCorner.cornerAlgebra
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_6
#print axioms Suzuki.IdempotentSystems.one_sub_shift_surjective
#print axioms Suzuki.CommonCorner.cornerRing._proof_18
#print axioms Suzuki.Target.instStarOrderedRingCarrier
#print axioms Suzuki.CommonCorner.cornerRing._proof_11
#print axioms Suzuki.StableFiniteness.FaithfulTrace.ctorIdx
#print axioms Suzuki.CommonCorner.cornerNormedAlgebra._proof_1
#print axioms Suzuki.CommonCorner.cornerRing._proof_20
#print axioms Suzuki.SimpleFullness.coe_closedIdeal
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_4
#print axioms Suzuki.MatrixDiagrams.second_square._abel_1_1
#print axioms Suzuki.InductiveAmalgam.System.rec
#print axioms Suzuki.PositiveLifting.coordinateEquiv._proof_2
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_11
#print axioms Suzuki.OrthogonalChannels.sum_mul
#print axioms Suzuki.PositiveLifting.exists_kernel_retraction
#print axioms Suzuki.CommonCorner.cornerRing._proof_2
#print axioms Suzuki.InductiveAmalgam.System.step
#print axioms Suzuki.IdempotentSystems.correction.eq_def
#print axioms Suzuki.Target.UnitalAlgebra.mk.inj
#print axioms Suzuki.StableFiniteness.matrixTrace_nonnegative
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.sizeOf_spec
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.representation_isometry
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv
#print axioms Suzuki.CommonCorner.FullProjection.exists_sum_one
#print axioms Suzuki.CommonCorner.rowCompression
#print axioms Suzuki.Target.IsSimple
#print axioms Suzuki.InductiveAmalgam.System.Hom.noConfusion
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv._proof_2
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_8
#print axioms Suzuki.CommonCorner.Frame.matrixHom_apply
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_9
#print axioms Suzuki.IdempotentSystems.correction._unsafe_rec
#print axioms Suzuki.MatrixDiagrams.diagram
#print axioms Suzuki.CommonCorner.Frame.representation._proof_9
#print axioms Suzuki.CommonCorner.compress
#print axioms Suzuki.IdempotentSystems.correction.eq_2
#print axioms Suzuki.CommonCorner.toCornerHom._proof_15
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_2
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.extension
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_4
#print axioms Suzuki.CommonCorner.Frame.matrixHom_isometry
#print axioms Suzuki.CommonCorner.cornerRing._proof_24
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.noConfusion
#print axioms Suzuki.InductiveAmalgam.System.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.coefficient_map
#print axioms Suzuki.CommonCorner.coe_one
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_9
#print axioms Suzuki.Target.IsPurelyInfinite
#print axioms Suzuki.InductiveAmalgam.System.mk.injEq
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_4
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv._proof_3
#print axioms Suzuki.CommonCorner.Frame.representation._proof_12
#print axioms Suzuki.CommonCorner.Frame.representation._proof_17
#print axioms Suzuki.CommonCorner.Frame.mk.sizeOf_spec
#print axioms Suzuki.InductiveAmalgam.System.Hom.noConfusionType
#print axioms Suzuki.CommonCorner.Frame.expand.eq_1
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_3
#print axioms Suzuki.PositiveLifting.coordinateEquiv._proof_1
#print axioms Suzuki.CommonCorner.Frame.representation._proof_7
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift.congr_simp
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_4
#print axioms Suzuki.PositiveLifting.exists_compatible_lifts._abel_1_1
#print axioms Suzuki.SimpleFullness.closedIdeal
#print axioms Suzuki.CommonCorner.cornerRing._proof_5
#print axioms Suzuki.CommonCorner.compress._proof_3
#print axioms Suzuki.CommonCorner.coe_star
#print axioms Suzuki.CommonCorner.coe_compress
#print axioms Suzuki.CommonCorner.Frame.star_support
#print axioms Suzuki.CommonCorner.compress._proof_2
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_1
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_7
#print axioms Suzuki.CommonCorner.cornerNormedRing._proof_2
#print axioms Suzuki.Target.UnitalAlgebra
#print axioms Suzuki.CommonCorner.map.congr_simp
#print axioms Suzuki.IdempotentSystems.correction.eq_1
#print axioms Suzuki.CommonCorner.coe_toCornerHom
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_1
#print axioms Suzuki.InductiveAmalgam.System.ctorIdx
#print axioms Suzuki.CommonCorner.cornerNormedRing._proof_1
#print axioms Suzuki.PositiveLifting.exists_positive_compatible_lifts
#print axioms Suzuki.CommonCorner.map._proof_6
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.closure_adjoin_eq_top
#print axioms Suzuki.CommonCorner.toCornerHom._proof_2
#print axioms Suzuki.CommonCorner.matrix_extension
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_5
#print axioms Suzuki.Target.UnitalAlgebra.mk.injEq
#print axioms Suzuki.Target.UnitalAlgebra.algebra
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.mk._flat_ctor
#print axioms Suzuki.CommonCorner.cornerRing
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_4
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_6
#print axioms Suzuki.PositiveLifting.Positive
#print axioms Suzuki.CommonCorner.Frame.coefficient_projection
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._simp_1_4
#print axioms Suzuki.CommonCorner.Frame.coe_gram_apply
#print axioms Suzuki.CommonCorner.Frame.matrixHom_injective
#print axioms Suzuki.IdempotentSystems.correction._f
#print axioms Suzuki.Target.UnitalAlgebra.mk
#print axioms Suzuki.InductiveAmalgam.System.casesOn
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.extension
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_2
#print axioms Suzuki.InductiveAmalgam.System.recOn
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_6
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_4
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_3
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_1
#print axioms Suzuki.MatrixDiagrams.kernel_action._abel_1_2
#print axioms Suzuki.SimpleFullness.exists_frame
#print axioms Suzuki.MatrixDiagrams.first_square
#print axioms Suzuki.CommonCorner.Frame.representation._proof_20
#print axioms Suzuki.CommonCorner.toCornerHom._proof_11
#print axioms Suzuki.CommonCorner.rowCompression._proof_6
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam
#print axioms Suzuki.CommonCorner.map._proof_10
#print axioms Suzuki.Target.UnitalAlgebra._sizeOf_inst
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.recOn
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_5
#print axioms Suzuki.CommonCorner.Frame.representation._proof_16
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_2
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_14
#print axioms Suzuki.Target.IsInfiniteProjection
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.eq_top_of_isClosed
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_4
#print axioms Suzuki.Target.instPartialOrderCarrier
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_7
#print axioms Suzuki.CommonCorner.Frame.coefficient_add
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_2
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_1
#print axioms Suzuki.Target.HasFiniteAmalgam
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_5
#print axioms Suzuki.SimpleTraces.mem_nullIdeal
#print axioms Suzuki.CommonCorner.FullProjection.exists_strictlyPositive_sum
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.commutes
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_3
#print axioms Suzuki.CommonCorner.cornerRing._proof_25
#print axioms Suzuki.CommonCorner.Frame.amplification
#print axioms Suzuki.InductiveAmalgam.System.Hom.ctorIdx
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_1
#print axioms Suzuki.CommonCorner.Frame.expand
#print axioms Suzuki.CommonCorner.inclusion
#print axioms Suzuki.CommonCorner.Frame.mk.noConfusion
#print axioms Suzuki.MatrixDiagrams.second_square._abel_1_2
#print axioms Suzuki.CommonCorner.map
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift_right
#print axioms Suzuki.CommonCorner.map._proof_16
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_1
#print axioms Suzuki.CommonCorner.isFullAmalgam_of_fullProjection
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_8
#print axioms Suzuki.CommonCorner.Frame.mk
#print axioms Suzuki.CommonCorner.Corner
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span._simp_1_3
#print axioms Suzuki.CommonCorner.Frame.mapFrame.congr_simp
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift.congr_simp
#print axioms Suzuki.CommonCorner.Frame.coefficient._simp_1
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_2
#print axioms Suzuki.CommonCorner.ofSupport
#print axioms Suzuki.CommonCorner.Frame.equivalence._proof_1
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra
#print axioms Suzuki.StableFiniteness.FaithfulTrace.casesOn
#print axioms Suzuki.StableFiniteness.IsStablyFinite
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_3
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv._proof_1
#print axioms Suzuki.CommonCorner.cornerClosed
#print axioms Suzuki.CommonCorner.isFullAmalgam_of_frame
#print axioms Suzuki.CommonCorner.map._proof_17
#print axioms Suzuki.CommonCorner.right_support
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_7
#print axioms Suzuki.Target.UnitalAlgebra.rec
#print axioms Suzuki.CommonCorner.Frame.eq_top_of_coefficients
#print axioms Suzuki.MatrixDiagrams.kernel_action._abel_1_3
#print axioms Suzuki.Target.IsFiniteConstituent
#print axioms Suzuki.OrthogonalChannels.compression
#print axioms Suzuki.CommonCorner.Frame.coefficient
#print axioms Suzuki.InductiveAmalgam.System.Hom
#print axioms Suzuki.CommonCorner.Frame.total
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_2
#print axioms Suzuki.CommonCorner.Frame.coe_coefficient
#print axioms Suzuki.Target.UnitalAlgebra.mk.sizeOf_spec
#print axioms Suzuki.CommonCorner.Frame.coefficient_star
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_1
#print axioms Suzuki.StableFiniteness.FaithfulTrace.rec
#print axioms Suzuki.InductiveAmalgam.System.Hom.rec
#print axioms Suzuki.CommonCorner.Frame._sizeOf_inst
#print axioms Suzuki.CommonCorner.cornerAlgebra._proof_2
#print axioms Suzuki.PositiveLifting.kernel_left_unimodular
#print axioms Suzuki.CommonCorner.Frame.noConfusion
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv_stage
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy
#print axioms Suzuki.InductiveAmalgam.System.mk.inj
#print axioms Suzuki.IdempotentSystems.correction._sunfold
#print axioms Suzuki.CommonCorner.Frame.representation._proof_10
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_1
#print axioms Suzuki.CommonCorner.Frame.coefficient_smul
#print axioms Suzuki.CommonCorner.Frame.mapFrame._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.eq_top_of_isClosed
#print axioms Suzuki.InductiveAmalgam.System
#print axioms Suzuki.CommonCorner.Frame.recOn
#print axioms Suzuki.MatrixDiagrams.first_square._abel_1_2
#print axioms Suzuki.CommonCorner.Frame.matrixHom_expand
#print axioms Suzuki.CommonCorner.map._proof_8
#print axioms Suzuki.CommonCorner.cornerRing._proof_12
#print axioms Suzuki.CommonCorner.Frame.equivalence._proof_3
#print axioms Suzuki.SimpleTraces.stablyFinite
#print axioms Suzuki.InductiveAmalgam.System.noConfusionType
#print axioms Suzuki.MatrixDiagrams.diagram.eq_1
#print axioms Suzuki.CommonCorner.Frame.ofApproximation
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.injEq
#print axioms Suzuki.PositiveLifting.Cokernel
#print axioms Suzuki.CommonCorner.rowCompression._proof_3
#print axioms Suzuki.SimpleTraces.nullIdeal_isClosed
#print axioms Suzuki.InductiveAmalgam.System.mk.noConfusion
#print axioms Suzuki.CommonCorner.toCornerHom._proof_8
#print axioms Suzuki.CommonCorner.strictlyPositive_sum_of_factorization
#print axioms Suzuki.CommonCorner.Frame.representation._proof_1
#print axioms Suzuki.SimpleFullness.full_of_nonzero
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.lift
#print axioms Suzuki.StableFiniteness.FaithfulTrace.toAddMonoidHom
#print axioms Suzuki.CommonCorner.map._proof_12
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift_comp_lift
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_4
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_10
#print axioms Suzuki.CommonCorner.cornerRing._aux_13
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_3
#print axioms Suzuki.CommonCorner.Frame.casesOn
#print axioms Suzuki.CommonCorner.compress._proof_1
#print axioms Suzuki.CommonCorner.toCornerHom._proof_17
#print axioms Suzuki.PositiveLifting.quotient
#print axioms Suzuki.CommonCorner.cornerRing._proof_21
#print axioms Suzuki.Target.MainClaim
#print axioms Suzuki.InductiveAmalgam.System.mk.sizeOf_spec
#print axioms Suzuki.PositiveLifting.exists_positive_homotopy._proof_1_3
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.commutes
#print axioms Suzuki.CommonCorner.Frame.rec
#print axioms Suzuki.CommonCorner.FullProjection.exists_frame
#print axioms Suzuki.CommonCorner.cornerRing._proof_15
#print axioms Suzuki.OrthogonalChannels.cross_mul
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_6
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.casesOn
#print axioms Suzuki.CommonCorner.inclusion_isometry
#print axioms Suzuki.PositiveLifting.Cokernel._proof_1
#print axioms Suzuki.CommonCorner.fullProjection_iff_exists_frame
#print axioms Suzuki.CommonCorner.Frame.mapFrame._proof_2
#print axioms Suzuki.StableFiniteness.matrixTrace.eq_1
#print axioms Suzuki.IdempotentSystems.correction
#print axioms Suzuki.CommonCorner.cornerSubalgebra._proof_1
#print axioms Suzuki.CommonCorner.cornerSubalgebra._proof_2
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.rec
#print axioms Suzuki.CommonCorner.toCornerHom._proof_9
#print axioms Suzuki.PositiveLifting.targetCokernelEquiv._proof_2
#print axioms Suzuki.Target.UnitalAlgebra.mk._flat_ctor
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_7
#print axioms Suzuki.CommonCorner.cornerRing._aux_22
#print axioms Suzuki.CommonCorner.map._proof_1
#print axioms Suzuki.InductiveAmalgam.isFullAmalgam_of_colimits
#print axioms Suzuki.SimpleTraces.nullIdeal.congr_simp
#print axioms Suzuki.IdempotentSystems.compatible_iff_constant_fixed
#print axioms Suzuki.Target.UnitalAlgebra.ctorIdx
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.injEq
#print axioms Suzuki.CommonCorner.Frame.coefficient._proof_1
#print axioms Suzuki.CommonCorner.exists_sum_of_mem_span._simp_1_1
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_2
#print axioms Suzuki.CommonCorner.Frame.representation_surjective
#print axioms Suzuki.SimpleFullness.closedIdeal._proof_4
#print axioms Suzuki.CommonCorner.Frame.gram
#print axioms Suzuki.PositiveLifting.simultaneous_positive_lifting._proof_1_2
#print axioms Suzuki.CommonCorner.cornerRing._proof_17
#print axioms Suzuki.CommonCorner.corner_eq_top_of_isClosed
#print axioms Suzuki.CommonCorner.Frame.mk.inj
#print axioms Suzuki.CommonCorner.Frame.ofApproximation._proof_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.rec
#print axioms Suzuki.SimpleTraces.null_right
#print axioms Suzuki.Target.UnitalAlgebra.casesOn
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.noConfusion
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.map_stage
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_4
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk._flat_ctor
#print axioms Suzuki.CommonCorner.Frame.coefficientSubalgebra._proof_5
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.lift_unique
#print axioms Suzuki.PositiveLifting.exists_large_unimodular
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv_isometry
#print axioms Suzuki.CommonCorner.cornerRing._proof_19
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._simp_1
#print axioms Suzuki.MatrixDiagrams.adjusted_kernel
#print axioms Suzuki.StableFiniteness.FaithfulTrace
#print axioms Suzuki.InductiveAmalgam.System._sizeOf_inst
#print axioms Suzuki.StableFiniteness.matrixTrace_faithful
#print axioms Suzuki.InductiveAmalgam.System.Hom.naturality
#print axioms Suzuki.StableFiniteness.amplification
#print axioms Suzuki.TracialFunctional.stablyFinite
#print axioms Suzuki.StableFiniteness.matrixTrace
#print axioms Suzuki.SimpleTraces.nullIdeal.eq_1
#print axioms Suzuki.CommonCorner.cornerNormedAlgebra
#print axioms Suzuki.CommonCorner.Frame.noConfusionType
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_8
#print axioms Suzuki.StableFiniteness.faithful_trace_stablyFinite
#print axioms Suzuki.CommonCorner.Frame.representation._proof_2
#print axioms Suzuki.InductiveAmalgam.System.obj
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.map
#print axioms Suzuki.OrthogonalChannels.cross_mul._simp_1_1
#print axioms Suzuki.CommonCorner.Frame.equivalence._proof_2
#print axioms Suzuki.InductiveAmalgam.System._sizeOf_1
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_9
#print axioms Suzuki.CommonCorner.Frame.coefficient_injective
#print axioms Suzuki.CommonCorner.Frame.representation_injective
#print axioms Suzuki.CommonCorner.Frame.ofStrictlyPositive._proof_5
#print axioms Suzuki.TracialFunctional.toFaithfulTrace._proof_2
#print axioms Suzuki.CommonCorner.compress_coe
#print axioms Suzuki.CommonCorner.Frame.corner_reconstruction
#print axioms Suzuki.OrthogonalChannels.sumHom_injective
#print axioms Suzuki.CommonCorner.Frame.representation
#print axioms Suzuki.CommonCorner.rowCompression._proof_2
#print axioms Suzuki.CommonCorner.toCornerHom._proof_19
#print axioms Suzuki.CommonCorner.Frame.matrixHom._proof_5
#print axioms Suzuki.CommonCorner.Frame.mapFrame
#print axioms Suzuki.MatrixDiagrams.kernel_action
#print axioms Suzuki.StableFiniteness.matrixTrace_cyclic
#print axioms Suzuki.CommonCorner.map._proof_2
#print axioms Suzuki.StableFiniteness.FaithfulTrace.mk.inj
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_7
#print axioms Suzuki.MatrixDiagrams.adjusted_chain
#print axioms Suzuki.InductiveAmalgam.System.Hom.casesOn
#print axioms Suzuki.Target.HasCPApproximation._proof_1
#print axioms Suzuki.SimpleTraces.nullIdeal._proof_2
#print axioms Suzuki.CommonCorner.cornerCStarAlgebra._proof_6
#print axioms Suzuki.InductiveAmalgam.IsSequentialColimit.equiv._proof_2
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.equiv_right
#print axioms Suzuki.InductiveAmalgam.System.Hom.mk.inj
#print axioms Suzuki.IdempotentSystems.one_sub_shift_surjective._abel_1_1
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.closure_adjoin_eq_top
#print axioms Suzuki.CommonCorner.coe_sum
#print axioms Suzuki.CStarAmalgam.IsFullAmalgam.mk._flat_ctor
#print axioms Suzuki.SimpleTraces.nullIdeal
#print axioms Suzuki.CommonCorner.compress._proof_5
#print axioms Suzuki.CommonCorner.cornerRing._proof_10
#print axioms Suzuki.CommonCorner.Frame.representation._proof_15
#print axioms Suzuki.CommonCorner.toCornerHom._proof_7
#print axioms Suzuki.OrthogonalChannels.sumHom._proof_5
#print axioms Suzuki.CommonCorner.cornerNonUnitalCStarAlgebra._proof_8
#print axioms Suzuki.IdempotentSystems.correction.match_1
#print axioms Suzuki.IdempotentSystems.correction_fixed
#print axioms Suzuki.PositiveLifting.exists_large_unimodular._proof_1_5
#print axioms Suzuki.CommonCorner.Frame.equivalence
#print axioms Suzuki.CommonCorner.cornerNormedRing
#print axioms Suzuki.CommonCorner.toCornerHom._proof_3
#print axioms Suzuki.TracialFunctional.toFaithfulTrace
#print axioms Suzuki.CommonCorner.Frame.representation._proof_6
#print axioms Suzuki.SimpleTraces.null_iff_norm
#print axioms Suzuki.CommonCorner.rowCompression._proof_4
#print axioms Suzuki.CommonCorner.Frame.representation._proof_3
