import Suzuki.CornerCPApproximation

/-!
# Pure infiniteness of concrete projection corners

Hereditary sets mean exactly `Target.hereditarySet`: the norm closure of the
range of `x ↦ b * x * b`. We prove that ambient hereditary sets generated by a
corner element lie inside that corner and that compression identifies the two
hereditary sets. Actual infinite-projection witnesses restrict to the corner.
No abstract Morita-invariance or hereditary-subalgebra theorem is assumed.

The final theorem gives the target's Kirchberg property for every nonzero
projection corner. It does not prove `Target.MainClaim`.
-/

noncomputable section

namespace Suzuki.CornerPureInfiniteness

open CommonCorner CornerCPApproximation
open scoped CStarAlgebra ComplexOrder

section Supports
variable {A : Type*} [CStarAlgebra A] {p : A} (hp : IsStarProjection p)

include hp

/-- Right support of the initial square forces right support of the element. -/
theorem right_support_of_square {v : A}
    (h : (star v * v) * p = star v * v) : v * p = v := by
  have hz : star (v * (1 - p)) * (v * (1 - p)) = 0 := by
    rw [star_mul, star_sub, star_one, hp.isSelfAdjoint.star_eq]
    calc
      (1 - p) * star v * (v * (1 - p)) =
          (1 - p) * ((star v * v) * (1 - p)) := by simp only [mul_assoc]
      _ = 0 := by rw [mul_sub, mul_one, h, sub_self, mul_zero]
  have hv := (CStarRing.star_mul_self_eq_zero_iff (v * (1 - p))).mp hz
  exact (sub_eq_zero.mp (by simpa only [mul_sub, mul_one] using hv)).symm

/-- Right support of the final square forces left support of the element. -/
theorem left_support_of_square {v : A}
    (h : (v * star v) * p = v * star v) : p * v = v := by
  have hs : star v * p = star v := right_support_of_square hp (v := star v)
    (by simpa only [star_star] using h)
  simpa only [star_mul, star_star, hp.isSelfAdjoint.star_eq] using congrArg star hs

/-- Compression is continuous into the corner's inherited norm topology. -/
theorem continuous_compress : Continuous (compress hp) := by
  exact ((continuous_const.mul continuous_id).mul continuous_const).subtype_mk _

/-- A sandwich by a supported element depends only on the compressed middle. -/
theorem compress_supported_sandwich (b : Corner hp) (a : A) :
    compress hp ((b : A) * a * (b : A)) = b * compress hp a * b := by
  apply Subtype.ext
  change p * ((b : A) * a * (b : A)) * p =
    (b : A) * (p * a * p) * (b : A)
  calc
    _ = ((p * (b : A)) * a) * ((b : A) * p) := by simp only [mul_assoc]
    _ = (b : A) * a * (b : A) := by rw [left_support, right_support]
    _ = ((b : A) * p) * a * (p * (b : A)) := by rw [left_support, right_support]
    _ = _ := by simp only [mul_assoc]

/-- Every ambient hereditary-set element generated by a corner element lies in
the same norm-closed projection corner. Positivity is unnecessary here. -/
theorem hereditary_subset_corner (b : Corner hp) :
    closure (Set.range fun a : A => (b : A) * a * (b : A)) ⊆
      (cornerSubalgebra hp : Set A) := by
  apply closure_minimal _ (cornerClosed hp)
  rintro x ⟨a, rfl⟩
  apply (Subsemigroup.mem_corner_iff hp.isIdempotentElem).mpr
  constructor
  · calc
      p * ((b : A) * a * (b : A)) = (p * (b : A)) * a * (b : A) := by
        simp only [mul_assoc]
      _ = _ := by rw [left_support]
  · calc
      ((b : A) * a * (b : A)) * p = (b : A) * a * ((b : A) * p) := by
        simp only [mul_assoc]
      _ = _ := by rw [right_support]

/-- Compression maps the ambient hereditary set into the internal hereditary set. -/
theorem compress_mem_hereditary (b : Corner hp) {x : A}
    (hx : x ∈ closure (Set.range fun a : A => (b : A) * a * (b : A))) :
    compress hp x ∈ closure (Set.range fun a : Corner hp => b * a * b) := by
  have hmaps : Set.MapsTo (compress hp)
      (Set.range fun a : A => (b : A) * a * (b : A))
      (Set.range fun a : Corner hp => b * a * b) := by
    rintro x ⟨a, rfl⟩
    exact ⟨compress hp a, (compress_supported_sandwich hp b a).symm⟩
  exact hmaps.closure (continuous_compress hp) hx

/-- Inclusion maps the internal hereditary set into the ambient hereditary set. -/
theorem coe_mem_hereditary (b : Corner hp) {x : Corner hp}
    (hx : x ∈ closure (Set.range fun a : Corner hp => b * a * b)) :
    (x : A) ∈ closure (Set.range fun a : A => (b : A) * a * (b : A)) := by
  have hmaps : Set.MapsTo (inclusion hp)
      (Set.range fun a : Corner hp => b * a * b)
      (Set.range fun a : A => (b : A) * a * (b : A)) := by
    rintro x ⟨a, rfl⟩
    exact ⟨(a : A), rfl⟩
  exact hmaps.closure (inclusion_isometry hp).continuous hx

/-- The two actual norm closures agree under corner inclusion. -/
theorem mem_hereditary_iff (b x : Corner hp) :
    x ∈ closure (Set.range fun a : Corner hp => b * a * b) ↔
      (x : A) ∈ closure (Set.range fun a : A => (b : A) * a * (b : A)) := by
  constructor
  · exact coe_mem_hereditary hp b
  · intro hx
    simpa only [compress_coe] using compress_mem_hereditary hp b hx

end Supports

set_option linter.style.haveILetI false in
/-- Infinite-projection witnesses for a supported projection actually belong to
the corner. The inequality on the final projection supplies its left support. -/
theorem isInfiniteProjection (B : Target.UnitalAlgebra) {p : B}
    (hp : IsStarProjection p) (r : Corner hp)
    (hr : Target.IsInfiniteProjection B (r : B)) :
    Target.IsInfiniteProjection ⟨Corner hp, inferInstance⟩ r := by
  -- The raw carrier is a subtype; pin its order and superclass instances to
  -- the spectral order used by the bundled target, rather than subtype order.
  letI : PartialOrder (Corner hp) := CStarAlgebra.spectralOrder (Corner hp)
  letI : StarOrderedRing (Corner hp) := CStarAlgebra.spectralOrderedRing (Corner hp)
  letI : Preorder (Corner hp) := (CStarAlgebra.spectralOrder (Corner hp)).toPreorder
  letI : LE (Corner hp) := (CStarAlgebra.spectralOrder (Corner hp)).toLE
  obtain ⟨hrproj, v, hv, hsproj, hsle, hsne⟩ := hr
  have hrle : (r : B) ≤ p :=
    (hrproj.le_iff_mul_eq_right hp).mpr (left_support hp r)
  have hsle' : v * star v ≤ p := hsle.trans hrle
  have hvl : p * v = v := left_support_of_square hp
    ((hsproj.le_iff_mul_eq_left hp).mp hsle')
  have hvr : v * p = v := right_support_of_square hp (by rw [hv, right_support])
  let w : Corner hp := ofSupport hp v hvl hvr
  have hrprojC : IsStarProjection r := by
    constructor
    · exact Subtype.ext hrproj.isIdempotentElem.eq
    · exact Subtype.ext hrproj.isSelfAdjoint.star_eq
  refine ⟨hrprojC, w, ?_, ?_, ?_, ?_⟩
  · exact Subtype.ext hv
  · constructor
    · exact Subtype.ext hsproj.isIdempotentElem.eq
    · exact Subtype.ext hsproj.isSelfAdjoint.star_eq
  · change (w * star w : Corner hp) ≤ r
    apply sub_nonneg.mp
    apply nonneg_of_injective_nonunital (inclusion hp) Subtype.val_injective
    exact sub_nonneg.mpr hsle
  · intro heq
    exact hsne (congrArg Subtype.val heq)

set_option linter.style.haveILetI false in
/-- Every projection corner inherits the target hereditary-set definition of
pure infiniteness, including the vacuous zero corner. -/
theorem isPurelyInfinite (B : Target.UnitalAlgebra) (hB : Target.IsPurelyInfinite B)
    {p : B} (hp : IsStarProjection p) :
    Target.IsPurelyInfinite ⟨Corner hp, inferInstance⟩ := by
  -- The raw carrier is a subtype; pin its order and superclass instances to
  -- the spectral order used by the bundled target, rather than subtype order.
  letI : PartialOrder (Corner hp) := CStarAlgebra.spectralOrder (Corner hp)
  letI : StarOrderedRing (Corner hp) := CStarAlgebra.spectralOrderedRing (Corner hp)
  letI : Preorder (Corner hp) := (CStarAlgebra.spectralOrder (Corner hp)).toPreorder
  letI : LE (Corner hp) := (CStarAlgebra.spectralOrder (Corner hp)).toLE
  intro b hb hne
  have hbC : (0 : Corner hp) ≤ b := hb
  have hbA : 0 ≤ (b : B) := map_nonneg (inclusion hp) hbC
  have hneA : (b : B) ≠ 0 := fun h => hne (Subtype.ext h)
  obtain ⟨r, hrher, hrinf⟩ := hB (b : B) hbA hneA
  let rC : Corner hp := ⟨r, hereditary_subset_corner hp b hrher⟩
  refine ⟨rC, ?_, isInfiniteProjection B hp rC hrinf⟩
  exact (mem_hereditary_iff hp b rC).mpr hrher

/-- Nonzero projection corners have all four exact target Kirchberg properties. -/
theorem isKirchberg (B : Target.UnitalAlgebra) (hB : Target.IsKirchberg B)
    {p : B} (hp : IsStarProjection p) (hne : p ≠ 0) :
    Target.IsKirchberg ⟨Corner hp, inferInstance⟩ := by
  let : TopologicalSpace.SeparableSpace B := hB.1
  exact ⟨CornerFiniteness.corner_separable hp,
    CornerCPApproximation.hasCPApproximation B hB.2.1 hp,
    CornerSimplicity.isSimple B hB.2.2.1 hp hne,
    isPurelyInfinite B hB.2.2.2 hp⟩

end Suzuki.CornerPureInfiniteness
