import Mathlib.Analysis.CStarAlgebra.Hom

/-!
# Full amalgams of complex unital C⋆-algebras

This file gives the genuine C⋆-algebraic universal property used by the
manuscript, and proves uniqueness of candidates by an isometric star algebra
equivalence. All homomorphisms here are complex-linear, multiplicative,
star-preserving and unital. The algebras have their actual complete C⋆-norms.

`IsFullAmalgam` quantifies over all complex unital C⋆-algebras in the fixed
universe `u`. It is a property of a supplied algebra and supplied maps; it
does not assert or construct a full amalgam for arbitrary input inclusions.
Injectivity of the input and output maps is a separate condition, not part of
the universal property. No nuclearity, KK-theory or classification statement
is encoded as an assumption or conclusion in this file.
-/

namespace Suzuki
namespace CStarAmalgam

universe u

variable {D A₀ A₁ P : Type u}
variable [CStarAlgebra D] [CStarAlgebra A₀] [CStarAlgebra A₁] [CStarAlgebra P]

/-- The full unital C⋆-amalgam universal property, in the universe `u`.
The commuting equation includes the specified copies of the common algebra.
Existence and uniqueness range over genuine unital complex star homomorphisms,
not arbitrary functions or an abstract surrogate for a C⋆-algebra. -/
structure IsFullAmalgam (i₀ : D →⋆ₐ[ℂ] A₀) (i₁ : D →⋆ₐ[ℂ] A₁)
    (j₀ : A₀ →⋆ₐ[ℂ] P) (j₁ : A₁ →⋆ₐ[ℂ] P) : Prop where
  commutes : j₀.comp i₀ = j₁.comp i₁
  extension : ∀ {C : Type u} [CStarAlgebra C]
    (f₀ : A₀ →⋆ₐ[ℂ] C) (f₁ : A₁ →⋆ₐ[ℂ] C),
    f₀.comp i₀ = f₁.comp i₁ →
      ∃! φ : P →⋆ₐ[ℂ] C, φ.comp j₀ = f₀ ∧ φ.comp j₁ = f₁

namespace IsFullAmalgam

variable {i₀ : D →⋆ₐ[ℂ] A₀} {i₁ : D →⋆ₐ[ℂ] A₁}
variable {j₀ : A₀ →⋆ₐ[ℂ] P} {j₁ : A₁ →⋆ₐ[ℂ] P}
variable (h : IsFullAmalgam i₀ i₁ j₀ j₁)
variable {C : Type u} [CStarAlgebra C]

/-- The extension supplied by a proved full-amalgam universal property. -/
noncomputable def lift (f₀ : A₀ →⋆ₐ[ℂ] C) (f₁ : A₁ →⋆ₐ[ℂ] C)
    (hf : f₀.comp i₀ = f₁.comp i₁) : P →⋆ₐ[ℂ] C :=
  (h.extension f₀ f₁ hf).choose

@[simp]
theorem lift_left (f₀ : A₀ →⋆ₐ[ℂ] C) (f₁ : A₁ →⋆ₐ[ℂ] C)
    (hf : f₀.comp i₀ = f₁.comp i₁) : (h.lift f₀ f₁ hf).comp j₀ = f₀ :=
  (h.extension f₀ f₁ hf).choose_spec.1.1

@[simp]
theorem lift_right (f₀ : A₀ →⋆ₐ[ℂ] C) (f₁ : A₁ →⋆ₐ[ℂ] C)
    (hf : f₀.comp i₀ = f₁.comp i₁) : (h.lift f₀ f₁ hf).comp j₁ = f₁ :=
  (h.extension f₀ f₁ hf).choose_spec.1.2

include h in
/-- Maps out of a full amalgam are determined by their two factor restrictions. -/
theorem hom_ext {φ ψ : P →⋆ₐ[ℂ] C}
    (h₀ : φ.comp j₀ = ψ.comp j₀) (h₁ : φ.comp j₁ = ψ.comp j₁) : φ = ψ := by
  have hc : (ψ.comp j₀).comp i₀ = (ψ.comp j₁).comp i₁ := by
    simp only [StarAlgHom.comp_assoc, h.commutes]
  obtain ⟨χ, _, hχ⟩ := h.extension (ψ.comp j₀) (ψ.comp j₁) hc
  exact (hχ φ ⟨h₀, h₁⟩).trans (hχ ψ ⟨rfl, rfl⟩).symm

/-- The chosen extension is the unique star homomorphism with the given
restrictions. This uses the universal property, not an assumed formula on words. -/
theorem lift_unique (f₀ : A₀ →⋆ₐ[ℂ] C) (f₁ : A₁ →⋆ₐ[ℂ] C)
    (hf : f₀.comp i₀ = f₁.comp i₁) (φ : P →⋆ₐ[ℂ] C)
    (h₀ : φ.comp j₀ = f₀) (h₁ : φ.comp j₁ = f₁) : φ = h.lift f₀ f₁ hf := by
  apply h.hom_ext
  · rw [h₀, h.lift_left]
  · rw [h₁, h.lift_right]

include h in
/-- The universal property forces the two factors to generate the supplied
algebra as a closed star algebra. In particular it rules out extraneous
summands in a proposed universal algebra. -/
theorem eq_top_of_isClosed (S : StarSubalgebra ℂ P) (hS : IsClosed (S : Set P))
    (h₀ : ∀ a, j₀ a ∈ S) (h₁ : ∀ a, j₁ a ∈ S) : S = ⊤ := by
  let : IsClosed (S : Set P) := hS
  let f₀ := j₀.codRestrict S h₀
  let f₁ := j₁.codRestrict S h₁
  have hf : f₀.comp i₀ = f₁.comp i₁ := by
    apply StarAlgHom.ext
    intro x
    exact Subtype.ext (DFunLike.congr_fun h.commutes x)
  let φ := h.lift f₀ f₁ hf
  have hφ : S.subtype.comp φ = StarAlgHom.id ℂ P := by
    apply h.hom_ext
    · change S.subtype.comp ((h.lift f₀ f₁ hf).comp j₀) = _
      rw [h.lift_left]
      exact StarAlgHom.subtype_comp_codRestrict j₀ S h₀
    · change S.subtype.comp ((h.lift f₀ f₁ hf).comp j₁) = _
      rw [h.lift_right]
      exact StarAlgHom.subtype_comp_codRestrict j₁ S h₁
  apply top_unique
  intro x _
  have hx : (φ x : P) = x := DFunLike.congr_fun hφ x
  exact hx ▸ (φ x).property

include h in
/-- The norm closure of the star algebra generated by both factor ranges is
the entire full amalgam. -/
theorem closure_adjoin_eq_top :
    (StarAlgebra.adjoin ℂ (Set.range j₀ ∪ Set.range j₁)).topologicalClosure = ⊤ := by
  apply h.eq_top_of_isClosed _ (StarSubalgebra.isClosed_topologicalClosure _)
  · intro a
    apply StarSubalgebra.le_topologicalClosure
    exact StarAlgebra.subset_adjoin _ _ (Set.mem_union_left _ ⟨a, rfl⟩)
  · intro a
    apply StarSubalgebra.le_topologicalClosure
    exact StarAlgebra.subset_adjoin _ _ (Set.mem_union_right _ ⟨a, rfl⟩)

variable {Q : Type u} [CStarAlgebra Q]
variable {k₀ : A₀ →⋆ₐ[ℂ] Q} {k₁ : A₁ →⋆ₐ[ℂ] Q}
variable (hQ : IsFullAmalgam i₀ i₁ k₀ k₁)

/-- The canonical maps between two candidates for the same full amalgam
are inverse. -/
theorem lift_comp_lift :
    (hQ.lift j₀ j₁ h.commutes).comp (h.lift k₀ k₁ hQ.commutes) =
      StarAlgHom.id ℂ P := by
  apply h.hom_ext
  · simp only [StarAlgHom.comp_assoc, lift_left, StarAlgHom.id_comp]
  · simp only [StarAlgHom.comp_assoc, lift_right, StarAlgHom.id_comp]

/-- Two actual full-amalgam candidates are canonically star algebra equivalent. -/
noncomputable def equiv : P ≃⋆ₐ[ℂ] Q :=
  StarAlgEquiv.ofBijective (h.lift k₀ k₁ hQ.commutes) (by
    have hleft : Function.LeftInverse (hQ.lift j₀ j₁ h.commutes)
        (h.lift k₀ k₁ hQ.commutes) := by
      intro x
      exact DFunLike.congr_fun (h.lift_comp_lift hQ) x
    have hright : Function.RightInverse (hQ.lift j₀ j₁ h.commutes)
        (h.lift k₀ k₁ hQ.commutes) := by
      intro x
      exact DFunLike.congr_fun (hQ.lift_comp_lift h) x
    exact ⟨hleft.injective, hright.surjective⟩)

/-- The canonical equivalence respects the first factor, not merely the abstract
isomorphism type of the product. -/
@[simp]
theorem equiv_left (a : A₀) : h.equiv hQ (j₀ a) = k₀ a :=
  DFunLike.congr_fun (h.lift_left k₀ k₁ hQ.commutes) a

/-- The canonical equivalence respects the second factor. -/
@[simp]
theorem equiv_right (a : A₁) : h.equiv hQ (j₁ a) = k₁ a :=
  DFunLike.congr_fun (h.lift_right k₀ k₁ hQ.commutes) a

/-- Uniqueness preserves the actual C⋆-norm, so it cannot replace the full
universal norm by a different completion. -/
theorem equiv_isometry : Isometry (h.equiv hQ : P → Q) :=
  NonUnitalStarAlgHom.isometry (h.equiv hQ) (h.equiv hQ).injective

end IsFullAmalgam

end CStarAmalgam
end Suzuki
