import Suzuki.FrameNormalization
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.Analysis.CStarAlgebra.Module.Constructions
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
import Mathlib.Analysis.Normed.Ring.Units
import Mathlib.Tactic

/-!
# From ideal-theoretic fullness to a finite frame

Fullness here means norm-density of the actual algebraic two-sided ideal
generated by the projection. It is not defined as existence of a frame.
-/

noncomputable section

namespace Suzuki.CommonCorner

open scoped CStarAlgebra

variable {A : Type*} [CStarAlgebra A]

/-- The closed two-sided ideal generated by `p` is the whole ambient algebra,
expressed directly as norm-density of its algebraic two-sided ideal. -/
def FullProjection (p : A) : Prop :=
  Dense (TwoSidedIdeal.span ({p} : Set A) : Set A)

/-- Elements of the algebraic ideal generated by one element are finite sums
of actual left and right multiples of that element. -/
theorem exists_sum_of_mem_span {p z : A}
    (hz : z ∈ TwoSidedIdeal.span ({p} : Set A)) :
    ∃ (n : ℕ) (a b : Fin n → A), ∑ i, a i * p * b i = z := by
  classical
  induction hz using TwoSidedIdeal.span_induction with
  | mem z hz =>
    have hz' : z = p := Set.mem_singleton_iff.mp hz
    subst z
    exact ⟨1, fun _ => 1, fun _ => 1, by simp⟩
  | zero => exact ⟨0, Fin.elim0, Fin.elim0, by simp⟩
  | add x y hx hy ihx ihy =>
    obtain ⟨n, a, b, hab⟩ := ihx
    obtain ⟨m, c, d, hcd⟩ := ihy
    refine ⟨n + m, Fin.addCases a c, Fin.addCases b d, ?_⟩
    rw [Fin.sum_univ_add]
    simpa using congrArg₂ (· + ·) hab hcd
  | neg x hx ih =>
    obtain ⟨n, a, b, hab⟩ := ih
    refine ⟨n, fun i => -a i, b, ?_⟩
    simpa only [neg_mul, Finset.sum_neg_distrib] using congrArg Neg.neg hab
  | left_absorb c x hx ih =>
    obtain ⟨n, a, b, hab⟩ := ih
    refine ⟨n, fun i => c * a i, b, ?_⟩
    simpa only [mul_assoc, ← Finset.mul_sum] using congrArg (c * ·) hab
  | right_absorb c x hx ih =>
    obtain ⟨n, a, b, hab⟩ := ih
    refine ⟨n, a, fun i => b i * c, ?_⟩
    simpa only [← mul_assoc, ← Finset.sum_mul] using congrArg (· * c) hab

/-- Norm-density of the actual ideal produces an exact finite expression for
one. The norm approximation is converted to a unit by the Neumann-series theorem. -/
theorem FullProjection.exists_sum_one {p : A} (hfull : FullProjection p) :
    ∃ (n : ℕ) (a b : Fin n → A), ∑ i, a i * p * b i = 1 := by
  obtain ⟨z, hz, hdist⟩ := Metric.mem_closure_iff.mp (hfull 1) 1 zero_lt_one
  have hnorm : ‖1 - z‖ < 1 := by simpa only [dist_eq_norm] using hdist
  have hu : IsUnit z := by
    simpa only [Units.val_oneSub, sub_sub_cancel] using (Units.oneSub (1 - z) hnorm).isUnit
  obtain ⟨u, rfl⟩ := hu
  obtain ⟨n, a, b, hab⟩ := exists_sum_of_mem_span hz
  refine ⟨n, fun i => (↑u⁻¹ : A) * a i, b, ?_⟩
  calc
    _ = (↑u⁻¹ : A) * ∑ i, a i * p * b i := by simp only [Finset.mul_sum, mul_assoc]
    _ = 1 := by rw [hab, Units.inv_mul]

section Positivity

variable [PartialOrder A] [StarOrderedRing A]

/-- A finite right factorization of the identity forces the corresponding
sum of positive squares to be invertible. The proof uses the actual
C*-algebra-valued Cauchy-Schwarz inequality on the finite standard module. -/
theorem strictlyPositive_sum_of_factorization {n : ℕ} (x b : Fin n → A)
    (hfactor : ∑ i, x i * b i = 1) :
    IsStrictlyPositive (∑ i, x i * star (x i)) := by
  let X : WithCStarModule A (Fin n → A) :=
    (WithCStarModule.equiv A (Fin n → A)).symm (fun i => star (b i))
  let Y : WithCStarModule A (Fin n → A) :=
    (WithCStarModule.equiv A (Fin n → A)).symm x
  have hXY : inner A X Y = 1 := by
    change (∑ i, x i * star (star (b i))) = 1
    simpa only [star_star] using hfactor
  have hYX : inner A Y X = 1 := by
    rw [← CStarModule.star_inner, hXY, star_one]
  have hCS : (1 : A) ≤ ‖X‖ ^ 2 • ∑ i, x i * star (x i) := by
    have h := CStarModule.inner_mul_inner_swap_le (A := A) (x := X) (y := Y)
    rw [hXY, hYX, one_mul] at h
    exact h
  let c : ℝ := ‖X‖ ^ 2 + 1
  have hc : 0 < c := by dsimp [c]; positivity
  have hq : 0 ≤ ∑ i, x i * star (x i) :=
    Finset.sum_nonneg fun _ _ => mul_star_self_nonneg _
  have hbig : IsStrictlyPositive (c • ∑ i, x i * star (x i)) := by
    apply isStrictlyPositive_one.of_le
    exact hCS.trans (smul_le_smul_of_nonneg_right (by dsimp [c]; linarith) hq)
  have h := hbig.smul (inv_pos.mpr hc)
  simpa only [smul_smul, inv_mul_cancel₀ (ne_of_gt hc), one_smul] using h

/-- Fullness supplies a finite supported family with invertible positive
square sum, before normalization. No frame-existence hypothesis is used. -/
theorem FullProjection.exists_strictlyPositive_sum {p : A}
    (hp : IsStarProjection p) (hfull : FullProjection p) :
    ∃ (n : ℕ) (x : Fin n → A), (∀ i, x i * p = x i) ∧
      IsStrictlyPositive (∑ i, x i * star (x i)) := by
  obtain ⟨n, a, b, hab⟩ := hfull.exists_sum_one
  refine ⟨n, fun i => a i * p, ?_, strictlyPositive_sum_of_factorization _ b hab⟩
  intro i
  rw [mul_assoc, hp.isIdempotentElem.eq]

end Positivity

/-- A finite frame implies ideal-theoretic fullness. This verifies the reverse
direction using the actual generated two-sided ideal. -/
theorem Frame.fullProjection {p : A} {hp : IsStarProjection p} {n : ℕ}
    (F : Frame hp n) : FullProjection p := by
  let I := TwoSidedIdeal.span ({p} : Set A)
  have hpI : p ∈ I := TwoSidedIdeal.subset_span (by simp)
  have hx (i : Fin n) : F.x i ∈ I := by
    rw [← F.support i]
    exact I.mul_mem_left _ _ hpI
  have hsum : (∑ i, F.x i * star (F.x i)) ∈ I := by
    exact sum_mem fun i _ => I.mul_mem_right _ _ (hx i)
  have hone : (1 : A) ∈ I := F.total ▸ hsum
  intro a
  apply subset_closure
  change a ∈ I
  simpa only [mul_one] using I.mul_mem_left a 1 hone

/-- Every genuinely full projection in a unital complex C*-algebra has a
finite frame. The order used to construct the inverse square root is the
canonical spectral order, supplied locally rather than assumed. -/
theorem FullProjection.exists_frame {p : A} (hp : IsStarProjection p)
    (hfull : FullProjection p) : ∃ n, Nonempty (Frame hp n) := by
  let : PartialOrder A := CStarAlgebra.spectralOrder A
  let : StarOrderedRing A := CStarAlgebra.spectralOrderedRing A
  obtain ⟨n, x, hsupport, hpositive⟩ := hfull.exists_strictlyPositive_sum hp
  exact ⟨n, ⟨Frame.ofStrictlyPositive hp x hsupport hpositive⟩⟩

/-- Norm-density of the generated ideal is equivalent to existence of a finite
frame. The left side remains the independent ideal-theoretic definition. -/
theorem fullProjection_iff_exists_frame {p : A} (hp : IsStarProjection p) :
    FullProjection p ↔ ∃ n, Nonempty (Frame hp n) := by
  constructor
  · exact FullProjection.exists_frame hp
  · rintro ⟨n, ⟨F⟩⟩
    exact F.fullProjection

section FullCorner

universe u

variable {D A₀ A₁ P : Type u}
variable [CStarAlgebra D] [CStarAlgebra A₀] [CStarAlgebra A₁] [CStarAlgebra P]
variable {i₀ : D →⋆ₐ[ℂ] A₀} {i₁ : D →⋆ₐ[ℂ] A₁}
variable {j₀ : A₀ →⋆ₐ[ℂ] P} {j₁ : A₁ →⋆ₐ[ℂ] P}

/-- The common-full-corner universal property from ideal-theoretic fullness.
All algebras have their genuine complete C*-norms. The conclusion is the
full unital universal property of the concrete corners with unit `p`,
including existence and uniqueness of extensions to every target algebra
in the fixed universe. No finite frame or desired corner amalgam is assumed. -/
theorem isFullAmalgam_of_fullProjection
    (h : CStarAmalgam.IsFullAmalgam i₀ i₁ j₀ j₁)
    {pD : D} {p₀ : A₀} {p₁ : A₁} {pP : P}
    (hpD : IsStarProjection pD) (hp₀ : IsStarProjection p₀)
    (hp₁ : IsStarProjection p₁) (hpP : IsStarProjection pP)
    (hi₀ : i₀ pD = p₀) (hi₁ : i₁ pD = p₁)
    (hj₀ : j₀ p₀ = pP) (hj₁ : j₁ p₁ = pP)
    (hfull : FullProjection pD) :
    CStarAmalgam.IsFullAmalgam
      (map hpD hp₀ i₀ hi₀) (map hpD hp₁ i₁ hi₁)
      (map hp₀ hpP j₀ hj₀) (map hp₁ hpP j₁ hj₁) := by
  obtain ⟨n, ⟨F⟩⟩ := hfull.exists_frame hpD
  exact isFullAmalgam_of_frame h hpD hp₀ hp₁ hpP hi₀ hi₁ hj₀ hj₁ F

end FullCorner

end Suzuki.CommonCorner
