import Suzuki.CStarAmalgam
import Suzuki.StableFiniteness
import Mathlib.Analysis.CStarAlgebra.CompletelyPositiveMap
import Mathlib.Analysis.CStarAlgebra.Projection
import Mathlib.RingTheory.TwoSidedIdeal.Lattice

/-!
# Intended full theorem: an open formal statement

`MainClaim` below is a proposition, NOT a theorem. No proof of it is supplied
or assumed. The definitions use actual complex C*-algebras, their norm topology,
completely positive approximations, matrix isometries, and the full universal
property. The correspondence of these conventions with the manuscript remains
an explicit review obligation, as does proving the proposition.
-/

namespace Suzuki
namespace Target

open scoped CStarAlgebra ComplexOrder

universe u

/-- A bundled unital complex C*-algebra, without assumed nuclearity or simplicity. -/
structure UnitalAlgebra where
  Carrier : Type u
  algebra : CStarAlgebra Carrier

attribute [instance] UnitalAlgebra.algebra

instance : CoeSort UnitalAlgebra.{u} (Type u) := ⟨UnitalAlgebra.Carrier⟩

noncomputable instance (A : UnitalAlgebra) : PartialOrder A :=
  CStarAlgebra.spectralOrder A

instance (A : UnitalAlgebra) : StarOrderedRing A :=
  CStarAlgebra.spectralOrderedRing A

/-- Closed two-sided ideal simplicity, with the zero algebra excluded. -/
def IsSimple (A : UnitalAlgebra) : Prop :=
  Nontrivial A ∧ ∀ I : TwoSidedIdeal A, IsClosed (I : Set A) → I = ⊥ ∨ I = ⊤

/-- Nuclearity expressed by completely positive contractive matrix approximation.
The equivalence with other definitions of nuclearity is not proved in this file. -/
def HasCPApproximation (A : UnitalAlgebra) : Prop :=
  ∀ (s : Finset A) (ε : ℝ), 0 < ε →
    ∃ (n : ℕ) (_ : 0 < n)
      (φ : A →CP CStarMatrix (Fin n) (Fin n) ℂ)
      (ψ : CStarMatrix (Fin n) (Fin n) ℂ →CP A),
      (∀ a, ‖φ a‖ ≤ ‖a‖) ∧ (∀ m, ‖ψ m‖ ≤ ‖m‖) ∧
      ∀ a ∈ s, ‖ψ (φ a) - a‖ < ε

/-- The norm-closed hereditary corner generated by a positive element, as a set. -/
def hereditarySet (A : UnitalAlgebra) (b : A) : Set A :=
  closure (Set.range fun x : A => b * x * b)

/-- An infinite projection has a proper equivalent subprojection. -/
def IsInfiniteProjection (A : UnitalAlgebra) (p : A) : Prop :=
  IsStarProjection p ∧ ∃ v : A,
    star v * v = p ∧ IsStarProjection (v * star v) ∧
      v * star v ≤ p ∧ v * star v ≠ p

/-- The hereditary-subalgebra criterion for simple pure infiniteness. -/
def IsPurelyInfinite (A : UnitalAlgebra) : Prop :=
  ∀ b : A, 0 ≤ b → b ≠ 0 →
    ∃ p : A, p ∈ hereditarySet A b ∧ IsInfiniteProjection A p

/-- The target hypotheses, using CP approximation for nuclearity. -/
def IsKirchberg (B : UnitalAlgebra) : Prop :=
  TopologicalSpace.SeparableSpace B ∧ HasCPApproximation B ∧
    IsSimple B ∧ IsPurelyInfinite B

/-- The properties required of each of the three finite constituents. -/
def IsFiniteConstituent (A : UnitalAlgebra) : Prop :=
  TopologicalSpace.SeparableSpace A ∧ HasCPApproximation A ∧
    IsSimple A ∧ StableFiniteness.IsStablyFinite A

/-- The actual target algebra itself satisfies the full amalgam universal property.
No quotient norm, reduced product, or opaque predicate is substituted. -/
def HasFiniteAmalgam (B : UnitalAlgebra.{u}) : Prop :=
  ∃ D A₀ A₁ : UnitalAlgebra.{u},
    IsFiniteConstituent D ∧ IsFiniteConstituent A₀ ∧ IsFiniteConstituent A₁ ∧
    ∃ (i₀ : D →⋆ₐ[ℂ] A₀) (i₁ : D →⋆ₐ[ℂ] A₁)
      (j₀ : A₀ →⋆ₐ[ℂ] B) (j₁ : A₁ →⋆ₐ[ℂ] B),
      Function.Injective i₀ ∧ Function.Injective i₁ ∧
        CStarAmalgam.IsFullAmalgam i₀ i₁ j₀ j₁

/-- OPEN PROPOSITION: the full claim still requiring a proof. -/
def MainClaim : Prop :=
  ∀ B : UnitalAlgebra.{u}, IsKirchberg B → HasFiniteAmalgam B

end Target
end Suzuki
