import Suzuki.FreeSelfAdjoint

/-! Uniform polynomial bounds for self-adjoint generators with arbitrary
individual norm bounds. This will construct universal algebras generated by
entire input Cstar algebras, without normalizing or postulating their norms. -/

noncomputable section
namespace Suzuki.WeightedFreeSelfAdjoint
open FreeSelfAdjoint
variable {ι : Type*}

theorem real_polynomial_bound {J : Type*} (C : J → Type*) [∀ j, CStarAlgebra (C j)]
    (f : ∀ j, ι → C j) (bound : ι → ℝ) (hf : ∀ j i, ‖f j i‖ ≤ bound i) (a : FreeAlgebra ℝ ι) :
    ∃ M : ℝ, 0 ≤ M ∧ ∀ j, ‖FreeAlgebra.lift ℝ (f j) a‖ ≤ M := by
  induction a using FreeAlgebra.induction with
  | grade0 r =>
    refine ⟨‖r‖, norm_nonneg _, ?_⟩
    intro j
    rw [AlgHom.commutes, Algebra.algebraMap_eq_smul_one, norm_smul]
    exact mul_le_of_le_one_right (norm_nonneg r) (IsStarProjection.one (C j)).norm_le
  | grade1 i => exact ⟨max 0 (bound i), le_max_left _ _, fun j => by
      simpa using (hf j i).trans (le_max_right 0 (bound i))⟩
  | add a b ha hb =>
    obtain ⟨M, hM, hMa⟩ := ha
    obtain ⟨N, hN, hNb⟩ := hb
    refine ⟨M+N, add_nonneg hM hN, fun j => ?_⟩
    rw [map_add]
    exact (norm_add_le _ _).trans (add_le_add (hMa j) (hNb j))
  | mul a b ha hb =>
    obtain ⟨M, hM, hMa⟩ := ha
    obtain ⟨N, hN, hNb⟩ := hb
    refine ⟨M*N, mul_nonneg hM hN, fun j => ?_⟩
    rw [map_mul]
    exact (norm_mul_le _ _).trans (mul_le_mul (hMa j) (hNb j) (norm_nonneg _) hM)

theorem polynomial_bound {J : Type*} (C : J → Type*) [∀ j, CStarAlgebra (C j)]
    (f : ∀ j, ι → C j) (hsa : ∀ j i, IsSelfAdjoint (f j i))
    (bound : ι → ℝ) (hf : ∀ j i, ‖f j i‖ ≤ bound i) (a : Algebra ι) :
    ∃ M : ℝ, 0 ≤ M ∧ ∀ j, ‖evaluate (f j) (hsa j) a‖ ≤ M := by
  induction a using TensorProduct.induction_on with
  | zero => exact ⟨0, le_rfl, fun j => by simp⟩
  | tmul z a =>
    obtain ⟨M, hM, hMa⟩ := real_polynomial_bound C f bound hf a
    refine ⟨‖z‖*M, mul_nonneg (norm_nonneg _) hM, fun j => ?_⟩
    rw [evaluate_tmul, norm_smul]
    exact mul_le_mul_of_nonneg_left (hMa j) (norm_nonneg z)
  | add a b ha hb =>
    obtain ⟨M, hM, hMa⟩ := ha
    obtain ⟨N, hN, hNb⟩ := hb
    refine ⟨M+N, add_nonneg hM hN, fun j => ?_⟩
    rw [map_add]
    exact (norm_add_le _ _).trans (add_le_add (hMa j) (hNb j))

/-- Weighted generators give a bounded family of actual star representations. -/
def boundedFamily {J : Type*} [Nonempty J] (C : J → Type*) [∀ j, CStarAlgebra (C j)]
    (f : ∀ j, ι → C j) (hsa : ∀ j i, IsSelfAdjoint (f j i))
    (bound : ι → ℝ) (hf : ∀ j i, ‖f j i‖ ≤ bound i) : UniversalCStar.BoundedFamily (Algebra ι) where
  Index := J
  index_nonempty := inferInstance
  target := C
  targetAlgebra := inferInstance
  hom j := evaluate (f j) (hsa j)
  bounded a := by
    obtain ⟨M, _, hM⟩ := polynomial_bound C f hsa bound hf a
    exact ⟨M, fun _ ⟨j, hj⟩ => hj ▸ hM j⟩


end Suzuki.WeightedFreeSelfAdjoint
